<?php
declare(strict_types=1);
require_once __DIR__.'/v10-lib.php';
require_once __DIR__.'/integrations.php';

function v10_condition_matches(array $condition,array $record): bool {
    if(!$condition)return true;$field=(string)($condition['field']??'');$op=(string)($condition['op']??'eq');$value=$condition['value']??null;$actual=$record[$field]??null;
    return match($op){'eq'=>(string)$actual===(string)$value,'neq'=>(string)$actual!==(string)$value,'contains'=>str_contains(mb_strtolower((string)$actual),mb_strtolower((string)$value)),'gt'=>(float)$actual>(float)$value,'gte'=>(float)$actual>=(float)$value,'lt'=>(float)$actual<(float)$value,'lte'=>(float)$actual<=(float)$value,'empty'=>$actual===null||$actual==='','not_empty'=>!($actual===null||$actual===''),default=>false};
}
function v10_action_template(string $text,array $record): string {return preg_replace_callback('/\{\{([A-Za-z0-9_]+)\}\}/',fn($m)=>(string)($record[$m[1]]??''),$text)??$text;}
function v10_execute_rule(array $rule,array $record,?int $entityId=null): array {
    $pdo=db();$cid=(int)$rule['company_id'];$action=v10_json_decode((string)$rule['action_json']);$status='success';$message='';
    try{
      switch($rule['action_type']){
        case 'create_task':$title=v10_action_template((string)($action['title']??'Automated task'),$record);$assignee=(int)($action['assignee_id']??($record['owner_id']??$record['manager_id']??0))?:null;$project=(int)($record['project_id']??($rule['entity_type']==='projects'?($entityId??0):0))?:null;$due=(int)($action['due_days']??1);$pdo->prepare("INSERT INTO tasks(company_id,project_id,title,description,assignee_id,created_by,status,priority,due_date) VALUES(?,?,?,?,?,?,'todo',?,DATE_ADD(NOW(),INTERVAL ? DAY))")->execute([$cid,$project,$title,(string)($action['description']??''),$assignee,$rule['created_by']?:null,(string)($action['priority']??'medium'),$due]);$message='task_created';break;
        case 'notify_user':$uid=(int)($action['user_id']??($record['owner_id']??$record['assignee_id']??0));if(!$uid)throw new RuntimeException('No target user');$title=v10_action_template((string)($action['title']??$rule['name']),$record);$body=v10_action_template((string)($action['body']??''),$record);$pdo->prepare('INSERT INTO notifications(company_id,user_id,title,body) VALUES(?,?,?,?)')->execute([$cid,$uid,$title,$body]);$message='notified';break;
        case 'change_owner':$entity=$rule['entity_type'];$m=v10_meta($entity);if(!$m['owner'])throw new RuntimeException('Entity has no owner');$uid=(int)($action['user_id']??0);tenant_ref('users',$uid,$cid,true);$pdo->prepare('UPDATE `'.$m['table'].'` SET '.v10_identifier($m['owner']).'=? WHERE id=? AND company_id=?')->execute([$uid,$entityId,$cid]);$message='owner_changed';break;
        case 'send_email':$to=v10_action_template((string)($action['to']??''),$record);if($to===''&&isset($record['email']))$to=(string)$record['email'];$cfg=integration_settings($cid,'email');if(!$cfg['enabled'])throw new RuntimeException('Email not configured');$subject=v10_action_template((string)($action['subject']??$rule['name']),$record);$body=v10_action_template((string)($action['body']??''),$record);[$ok,$msg]=smtp_send($cfg['settings'],$to,$subject,nl2br(e($body)));log_communication($cid,null,'email',$to,$subject,$body,$ok?'sent':'failed',$cfg['provider'],$ok?'':$msg);if(!$ok)throw new RuntimeException($msg);$message='email_sent';break;
        case 'send_sms':$to=v10_action_template((string)($action['to']??''),$record);if($to===''&&isset($record['phone']))$to=(string)$record['phone'];$cfg=integration_settings($cid,'sms');if(!$cfg['enabled'])throw new RuntimeException('SMS not configured');$body=v10_action_template((string)($action['body']??$rule['name']),$record);[$ok,$msg]=sms_send_v10($cfg['provider'],$cfg['settings'],$to,$body);log_communication($cid,null,'sms',$to,$rule['name'],$body,$ok?'sent':'failed',$cfg['provider'],$ok?'':$msg);if(!$ok)throw new RuntimeException($msg);$message='sms_sent';break;
        default:throw new RuntimeException('Unknown workflow action');
      }
    }catch(Throwable $e){$status='failed';$message=$e->getMessage();}
    $pdo->prepare('INSERT INTO v10_workflow_runs(company_id,rule_id,entity_type,entity_id,status,message) VALUES(?,?,?,?,?,?)')->execute([$cid,$rule['id'],$rule['entity_type'],$entityId,$status,$message]);return[$status==='success',$message];
}
function v10_run_event_rules(int $cid,string $entity,string $trigger,array $record,?int $entityId=null,?string $field=null): void {
    $pdo=db();$sql='SELECT * FROM v10_workflow_rules WHERE company_id=? AND entity_type=? AND trigger_type=? AND enabled=1';$args=[$cid,$entity,$trigger];if($field!==null){$sql.=' AND (trigger_field IS NULL OR trigger_field=? )';$args[]=$field;}$st=$pdo->prepare($sql);$st->execute($args);foreach($st as $rule){$cond=v10_json_decode((string)$rule['condition_json']);if(v10_condition_matches($cond,$record))v10_execute_rule($rule,$record,$entityId);}
}
function sms_send_v10(string $provider,array $cfg,string $to,string $message): array {
    if(!function_exists('curl_init'))return[false,'PHP cURL extension is required'];$provider=strtolower($provider);
    if(str_contains($provider,'kavenegar')){$key=(string)($cfg['api_key']??$cfg['token']??'');if(!$key)return[false,'Kavenegar API key missing'];$url='https://api.kavenegar.com/v1/'.rawurlencode($key).'/sms/send.json';$data=['receptor'=>$to,'message'=>$message];if(!empty($cfg['sender']))$data['sender']=$cfg['sender'];return v10_http_form($url,$data,[]);}
    if(str_contains($provider,'melipayamak')){$url=(string)($cfg['url']??'https://rest.payamak-panel.com/api/SendSMS/SendSMS');$data=['username'=>$cfg['username']??'','password'=>$cfg['password']??'','to'=>$to,'from'=>$cfg['sender']??'','text'=>$message,'isflash'=>false];return v10_http_json($url,$data,[]);}
    if(str_contains($provider,'sms.ir')){$url=(string)($cfg['url']??'https://api.sms.ir/v1/send/bulk');$headers=['X-API-KEY: '.($cfg['api_key']??$cfg['token']??'')];$data=['lineNumber'=>$cfg['sender']??'','MessageText'=>$message,'Mobiles'=>[$to]];return v10_http_json($url,$data,$headers);}
    return sms_send($cfg,$to,$message);
}
function v10_provider_response_ok(int $code,string $body,string $error): bool {if($error!==''||$code<200||$code>=300)return false;$j=json_decode($body,true);if(!is_array($j))return !preg_match('/\b(error|failed|failure)\b/i',$body);foreach(['success','ok'] as $key)if(array_key_exists($key,$j)&&!filter_var($j[$key],FILTER_VALIDATE_BOOL))return false;if(!empty($j['error'])||!empty($j['errors']))return false;if(isset($j['return']['status'])&&(int)$j['return']['status']!==200)return false;if(isset($j['RetStatus'])&&(int)$j['RetStatus']!==1)return false;foreach(['status','statusCode','code'] as $key){if(!isset($j[$key])||is_array($j[$key]))continue;$value=$j[$key];if(in_array(strtolower((string)$value),['error','failed','failure','false'],true))return false;if(is_numeric($value)&&((int)$value<0||(int)$value>=400))return false;}return true;}
function v10_http_form(string $url,array $data,array $headers): array {$ch=curl_init($url);curl_setopt_array($ch,[CURLOPT_POST=>true,CURLOPT_POSTFIELDS=>http_build_query($data),CURLOPT_HTTPHEADER=>$headers,CURLOPT_RETURNTRANSFER=>true,CURLOPT_TIMEOUT=>20]);$resp=(string)curl_exec($ch);$code=(int)curl_getinfo($ch,CURLINFO_HTTP_CODE);$err=curl_error($ch);curl_close($ch);return[v10_provider_response_ok($code,$resp,$err),$err?:($resp?:'HTTP '.$code)];}
function v10_http_json(string $url,array $data,array $headers): array {$headers=array_merge(['Content-Type: application/json'],$headers);$ch=curl_init($url);curl_setopt_array($ch,[CURLOPT_POST=>true,CURLOPT_POSTFIELDS=>json_encode($data,JSON_UNESCAPED_UNICODE),CURLOPT_HTTPHEADER=>$headers,CURLOPT_RETURNTRANSFER=>true,CURLOPT_TIMEOUT=>20]);$resp=(string)curl_exec($ch);$code=(int)curl_getinfo($ch,CURLINFO_HTTP_CODE);$err=curl_error($ch);curl_close($ch);return[v10_provider_response_ok($code,$resp,$err),$err?:($resp?:'HTTP '.$code)];}
