<?php
declare(strict_types=1);
require __DIR__.'/automation-engine.php';
if(PHP_SAPI!=='cli'){$key=(string)envv('CRON_KEY','');if($key===''||!hash_equals($key,(string)($_GET['key']??''))){http_response_code(403);exit('Forbidden');}}
$pdo=db();$processed=0;$failed=0;
function auto_reminder(PDO $pdo,string $sql,array $args=[]): void {$st=$pdo->prepare($sql);$st->execute($args);}
// Due/overdue sources. INSERT IGNORE relies on reminders.source_key being unique in V9 migration.
$pdo->exec("INSERT IGNORE INTO reminders(company_id,user_id,entity_type,entity_id,source_key,title,message,remind_at,recurrence,channels,status,created_by) SELECT t.company_id,t.assignee_id,'tasks',t.id,CONCAT('v10:task:',t.id),CONCAT('Task due: ',t.title),CONCAT('Due ',DATE_FORMAT(t.due_date,'%Y-%m-%d %H:%i')),NOW(),'none','in_app,email','pending',t.created_by FROM tasks t LEFT JOIN v10_record_deletions d ON d.company_id=t.company_id AND d.entity_type='tasks' AND d.entity_id=t.id WHERE d.id IS NULL AND t.assignee_id IS NOT NULL AND t.status<>'done' AND t.due_date IS NOT NULL AND t.due_date<=DATE_ADD(NOW(),INTERVAL 24 HOUR)");
$pdo->exec("INSERT IGNORE INTO reminders(company_id,user_id,entity_type,entity_id,source_key,title,message,remind_at,recurrence,channels,status,created_by) SELECT f.company_id,f.assigned_to,'followups',f.id,CONCAT('v10:followup:',f.id),CONCAT('Follow-up due: ',f.subject),CONCAT('Due ',DATE_FORMAT(f.due_at,'%Y-%m-%d %H:%i')),NOW(),'none','in_app,email','pending',f.assigned_to FROM followups f LEFT JOIN v10_record_deletions d ON d.company_id=f.company_id AND d.entity_type='followups' AND d.entity_id=f.id WHERE d.id IS NULL AND f.assigned_to IS NOT NULL AND f.status='open' AND f.due_at IS NOT NULL AND f.due_at<=DATE_ADD(NOW(),INTERVAL 24 HOUR)");
$pdo->exec("INSERT IGNORE INTO reminders(company_id,user_id,entity_type,entity_id,source_key,title,message,remind_at,recurrence,channels,status,created_by) SELECT p.company_id,u.id,'payments',p.id,CONCAT('v10:payment:',p.id,':',u.id),CONCAT('Payment due: ',p.title),CONCAT(p.amount,' ',p.currency,' · due ',COALESCE(DATE_FORMAT(p.due_date,'%Y-%m-%d'),'—')),NOW(),'none','in_app,email','pending',u.id FROM payment_milestones p JOIN users u ON u.company_id=p.company_id AND u.active=1 AND u.role IN ('super_admin','company_admin','finance') LEFT JOIN v10_record_deletions d ON d.company_id=p.company_id AND d.entity_type='payments' AND d.entity_id=p.id WHERE d.id IS NULL AND p.status<>'paid' AND p.due_date IS NOT NULL AND p.due_date<=DATE_ADD(CURDATE(),INTERVAL 2 DAY)");
$pdo->exec("INSERT IGNORE INTO reminders(company_id,user_id,entity_type,entity_id,source_key,title,message,remind_at,recurrence,channels,status,created_by) SELECT l.company_id,u.id,'lcs',l.id,CONCAT('v10:lc:',l.id,':',u.id),CONCAT('LC expiry: ',l.lc_no),CONCAT('Expires ',DATE_FORMAT(l.expiry_date,'%Y-%m-%d')),NOW(),'none','in_app,email','pending',u.id FROM lc_records l JOIN users u ON u.company_id=l.company_id AND u.active=1 AND u.role IN ('super_admin','company_admin','finance','manager') LEFT JOIN v10_record_deletions d ON d.company_id=l.company_id AND d.entity_type='lcs' AND d.entity_id=l.id WHERE d.id IS NULL AND l.status NOT IN ('paid','closed') AND l.expiry_date IS NOT NULL AND l.expiry_date<=DATE_ADD(CURDATE(),INTERVAL 7 DAY)");
$pdo->exec("INSERT IGNORE INTO reminders(company_id,user_id,entity_type,entity_id,source_key,title,message,remind_at,recurrence,channels,status,created_by) SELECT s.company_id,u.id,'shipments',s.id,CONCAT('v10:shipment:',s.id,':',u.id),CONCAT('Shipment ETA: ',s.shipment_no),CONCAT('ETA ',DATE_FORMAT(s.eta,'%Y-%m-%d')),NOW(),'none','in_app,email','pending',u.id FROM shipments s JOIN users u ON u.company_id=s.company_id AND u.active=1 AND u.role IN ('super_admin','company_admin','manager','project_manager','sales') LEFT JOIN v10_record_deletions d ON d.company_id=s.company_id AND d.entity_type='shipments' AND d.entity_id=s.id WHERE d.id IS NULL AND s.status NOT IN ('delivered','cancelled') AND s.eta IS NOT NULL AND s.eta<=DATE_ADD(CURDATE(),INTERVAL 2 DAY)");
// Date reached rules. Trigger field contains a table column from the whitelisted entity meta.
$st=$pdo->query("SELECT * FROM v10_workflow_rules WHERE enabled=1 AND trigger_type='date_reached'");foreach($st as $rule){try{$m=v10_meta((string)$rule['entity_type']);$field=(string)$rule['trigger_field'];if(!$field||!in_array($field,$m['fields'],true))continue;$q=$pdo->prepare('SELECT t.* FROM `'.$m['table'].'` t WHERE t.company_id=? AND '.v10_is_deleted_sql('t').' AND '.v10_identifier($field).' IS NOT NULL AND '.v10_identifier($field).'<=NOW() ORDER BY id DESC LIMIT 100');$q->execute([$rule['company_id'],$rule['entity_type']]);foreach($q as $record){$dupe=$pdo->prepare('SELECT 1 FROM v10_workflow_runs WHERE company_id=? AND rule_id=? AND entity_type=? AND entity_id=? LIMIT 1');$dupe->execute([$rule['company_id'],$rule['id'],$rule['entity_type'],$record['id']]);if(!$dupe->fetchColumn()&&v10_condition_matches(v10_json_decode((string)$rule['condition_json']),$record))v10_execute_rule($rule,$record,(int)$record['id']);}}catch(Throwable $e){error_log('workflow cron: '.$e->getMessage());}}
// Pull IMAP for every enabled email integration; failures remain isolated per company.
$st=$pdo->query("SELECT DISTINCT company_id FROM integration_settings WHERE provider_type='email' AND enabled=1");foreach($st as $mailCompany){try{imap_sync_v10((int)$mailCompany['company_id'],100);}catch(Throwable $e){error_log('imap cron: '.$e->getMessage());}}
// Apply configured SLA deadlines and notify the owner (or company admins) once on breach.
$st=$pdo->query("SELECT id,company_id,priority,created_at FROM v10_tickets WHERE sla_due_at IS NULL AND status NOT IN ('resolved','closed') LIMIT 500");foreach($st as $ticket){$pol=json_decode((string)v10_company_setting((int)$ticket['company_id'],'sla_policies','{}'),true)?:[];$hours=max(1,(int)($pol[$ticket['priority']]??24));$due=date('Y-m-d H:i:s',strtotime((string)$ticket['created_at'])+$hours*3600);$pdo->prepare('UPDATE v10_tickets SET sla_due_at=? WHERE id=? AND company_id=?')->execute([$due,$ticket['id'],$ticket['company_id']]);}
$pdo->exec("INSERT IGNORE INTO notifications(company_id,user_id,title,body) SELECT t.company_id,u.id,CONCAT('SLA breached: ',t.ticket_no),t.subject FROM v10_tickets t JOIN users u ON u.company_id=t.company_id AND u.active=1 AND (u.id=t.owner_id OR (t.owner_id IS NULL AND u.role IN ('company_admin','super_admin'))) LEFT JOIN v10_sla_alerts a ON a.company_id=t.company_id AND a.ticket_id=t.id WHERE a.ticket_id IS NULL AND t.status NOT IN ('resolved','closed') AND t.sla_due_at<NOW()");
$pdo->exec("INSERT IGNORE INTO v10_sla_alerts(company_id,ticket_id) SELECT company_id,id FROM v10_tickets WHERE status NOT IN ('resolved','closed') AND sla_due_at<NOW()");
// Customer ETA SMS: one notification per shipment and ETA date.
$st=$pdo->query("SELECT s.*,c.phone customer_phone FROM shipments s JOIN customers c ON c.id=s.customer_id LEFT JOIN v10_shipment_eta_alerts a ON a.company_id=s.company_id AND a.shipment_id=s.id AND a.eta=s.eta WHERE a.shipment_id IS NULL AND c.phone IS NOT NULL AND c.phone<>'' AND s.status NOT IN ('delivered','cancelled') AND s.eta BETWEEN CURDATE() AND DATE_ADD(CURDATE(),INTERVAL 2 DAY)");foreach($st as $ship){try{$cfg=integration_settings((int)$ship['company_id'],'sms');if(!$cfg['enabled'])continue;$message='Shipment '.$ship['shipment_no'].' ETA: '.$ship['eta'];[$ok,$msg]=sms_send_v10($cfg['provider'],$cfg['settings'],$ship['customer_phone'],$message);log_communication((int)$ship['company_id'],null,'sms',$ship['customer_phone'],'Shipment ETA',$message,$ok?'sent':'failed',$cfg['provider'],$ok?'':$msg);if($ok)$pdo->prepare('INSERT IGNORE INTO v10_shipment_eta_alerts(company_id,shipment_id,eta) VALUES(?,?,?)')->execute([$ship['company_id'],$ship['id'],$ship['eta']]);else$failed++;}catch(Throwable $e){$failed++;error_log('shipment ETA SMS: '.$e->getMessage());}}
// Deliver reminders.
$st=$pdo->query("SELECT r.*,u.email,u.phone FROM reminders r JOIN users u ON u.id=r.user_id WHERE r.status='pending' AND r.remind_at<=NOW() ORDER BY r.remind_at LIMIT 300");foreach($st as $r){try{$channels=array_filter(array_map('trim',explode(',',(string)$r['channels'])));if(in_array('in_app',$channels,true)||!$channels)$pdo->prepare('INSERT INTO notifications(company_id,user_id,title,body) VALUES(?,?,?,?)')->execute([$r['company_id'],$r['user_id'],$r['title'],$r['message']]);if(in_array('email',$channels,true)&&$r['email']){$cfg=integration_settings((int)$r['company_id'],'email');if($cfg['enabled']){[$ok,$msg]=smtp_send($cfg['settings'],$r['email'],$r['title'],nl2br(e((string)$r['message'])));log_communication((int)$r['company_id'],(int)$r['user_id'],'email',$r['email'],$r['title'],(string)$r['message'],$ok?'sent':'failed',$cfg['provider'],$ok?'':$msg);if(!$ok)$failed++;}}if(in_array('sms',$channels,true)&&$r['phone']){$cfg=integration_settings((int)$r['company_id'],'sms');if($cfg['enabled']){[$ok,$msg]=sms_send_v10($cfg['provider'],$cfg['settings'],$r['phone'],(string)($r['message']?:$r['title']));log_communication((int)$r['company_id'],(int)$r['user_id'],'sms',$r['phone'],$r['title'],(string)$r['message'],$ok?'sent':'failed',$cfg['provider'],$ok?'':$msg);if(!$ok)$failed++;}}$next=match($r['recurrence']){'daily'=>'DATE_ADD(remind_at,INTERVAL 1 DAY)','weekly'=>'DATE_ADD(remind_at,INTERVAL 1 WEEK)','monthly'=>'DATE_ADD(remind_at,INTERVAL 1 MONTH)',default=>null};if($next)$pdo->exec('UPDATE reminders SET last_sent_at=NOW(),remind_at='.$next.' WHERE id='.(int)$r['id']);else$pdo->prepare("UPDATE reminders SET last_sent_at=NOW(),status='sent' WHERE id=?")->execute([$r['id']]);$processed++;}catch(Throwable $e){$failed++;error_log('v10 reminder '.$r['id'].': '.$e->getMessage());}}
echo "processed=$processed failed=$failed\n";
