<?php
declare(strict_types=1);require __DIR__.'/v10-lib.php';$u=current_user();if(!$u){header('Location:login.php');exit;}$caps=v10_caps()[$u['role']]??[];$company=['name'=>$u['company_name'],'logo'=>$u['logo_url']??null,'primary'=>$u['primary_color']?:'#173f35','accent'=>$u['accent_color']?:'#bd9856'];?><!doctype html>
<html lang="fa" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="<?=$company['primary']?>"><title><?=e($company['name'])?> · <?=e(APP_PRODUCT_NAME)?></title><link rel="manifest" href="manifest.webmanifest"><link rel="stylesheet" href="assets/app.css?v=<?=APP_VERSION?>"></head><body>
<div class="app" id="app"><aside class="sidebar" id="sidebar"><div class="brand"><div class="brand-logo"><?php if(!empty($company['logo'])):?><img src="<?=e($company['logo'])?>" alt=""><?php else:?><?=e(mb_substr($company['name'],0,1))?><?php endif;?></div><div class="brand-copy"><b><?=e($company['name'])?></b><small data-i="workspace">فضای کاری CRM</small></div><button class="icon-btn collapse-btn" id="collapseSide" aria-label="collapse">‹</button></div><nav id="nav" class="nav"></nav><div class="side-user"><div class="avatar"><?=e(mb_substr($u['name'],0,1))?></div><div class="side-user-copy"><b><?=e($u['name'])?></b><small><?=e($u['title']?:$u['role'])?></small></div><button class="icon-btn" id="userMenuBtn">⋮</button></div></aside>
<main class="workspace"><header class="topbar"><button class="icon-btn mobile-only" id="mobileMenu">☰</button><button class="global-search" id="globalSearch"><span>⌕</span><span data-i="globalSearch">جست‌وجوی سراسری</span><kbd>Ctrl K</kbd></button><div class="top-actions"><?php if($config['mode']==='offline'):?><span class="offline-chip">OFFLINE</span><?php endif?><button class="icon-btn" id="notificationBtn" aria-label="notifications">🔔<span id="notifBadge" class="count-badge hidden">0</span></button><button class="btn primary" id="quickCreate">＋ <span data-i="create">ایجاد</span></button><button class="chip" id="langBtn">EN</button><button class="icon-btn" id="themeBtn">◐</button></div></header><section id="page" class="page"></section><footer class="app-footer"><?=app_credit_html()?> · <button id="aboutBtn" data-i="about">درباره</button></footer></main></div>
<nav class="bottom-nav" id="bottomNav"></nav><div id="modalRoot"></div><div id="toastRoot" class="toast-root"></div><div id="commandRoot"></div>
<script>window.APP_BOOT=<?=json_encode(['user'=>['id'=>(int)$u['id'],'name'=>$u['name'],'email'=>$u['email'],'phone'=>$u['phone'],'role'=>$u['role'],'lang'=>$u['lang']],'caps'=>$caps,'company'=>$company,'csrf'=>csrf_token(),'version'=>APP_VERSION,'mode'=>$config['mode'],'credit'=>APP_CREDIT],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)?>;</script>
<script src="assets/app.js?v=<?=APP_VERSION?>"></script>
<script src="assets/js/dashboard.js?v=<?=APP_VERSION?>"></script><script src="assets/js/records.js?v=<?=APP_VERSION?>"></script><script src="assets/js/pipeline.js?v=<?=APP_VERSION?>"></script><script src="assets/js/trade.js?v=<?=APP_VERSION?>"></script><script src="assets/js/automation.js?v=<?=APP_VERSION?>"></script><script src="assets/js/communications.js?v=<?=APP_VERSION?>"></script><script src="assets/js/sales.js?v=<?=APP_VERSION?>"></script><script src="assets/js/service.js?v=<?=APP_VERSION?>"></script><script src="assets/js/reports.js?v=<?=APP_VERSION?>"></script><script src="assets/js/data.js?v=<?=APP_VERSION?>"></script><script src="assets/js/admin.js?v=<?=APP_VERSION?>"></script><script src="assets/js/onboarding.js?v=<?=APP_VERSION?>"></script><script src="assets/js/notifications.js?v=<?=APP_VERSION?>"></script><script src="assets/js/record-extras.js?v=<?=APP_VERSION?>"></script><script src="assets/js/orders-v10.js?v=<?=APP_VERSION?>"></script><script src="assets/js/settings-v10.js?v=<?=APP_VERSION?>"></script><script src="assets/js/support-v10.js?v=<?=APP_VERSION?>"></script>
<script src="assets/js/incoming-calls.js?v=<?=APP_VERSION?>"></script><script src="assets/js/deployment.js?v=<?=APP_VERSION?>"></script><script src="assets/js/deployment-settings.js?v=<?=APP_VERSION?>"></script><script src="assets/js/help.js?v=<?=APP_VERSION?>"></script><script src="assets/js/ai.js?v=<?=APP_VERSION?>"></script></body></html>
