<?php
declare(strict_types=1);
require_once __DIR__.'/product.php';
require_once __DIR__.'/migration-runner.php';

function inst_e(mixed $v): string { return htmlspecialchars((string)$v,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8'); }
function fld(string $label,string $name,string $value='',string $type='text',bool $required=true): string {return '<label class="field"><span>'.inst_e($label).'</span><input name="'.inst_e($name).'" value="'.inst_e($value).'" type="'.inst_e($type).'"'.($required?' required':'').'></label>';}
function env_read_simple(string $path): array {$out=[];if(!is_file($path))return$out;foreach(file($path,FILE_IGNORE_NEW_LINES|FILE_SKIP_EMPTY_LINES)?:[]as$line){$line=trim($line);if($line===''||$line[0]==='#'||!str_contains($line,'='))continue;[$key,$value]=explode('=',$line,2);$out[trim($key)]=trim(trim($value),"\"'");}return$out;}
function env_write(string $path,array $data): void {$lines=[];foreach($data as$key=>$value){$value=(string)$value;if(preg_match('/[\s#=]/',$value))$value='"'.str_replace(['\\','"'],['\\\\','\\"'],$value).'"';$lines[]=$key.'='.$value;}if(file_put_contents($path,implode(PHP_EOL,$lines).PHP_EOL,LOCK_EX)===false)throw new RuntimeException('Cannot write .env');}
function requirements(): array {$storage=__DIR__.'/storage';return[['PHP 8.2+',version_compare(PHP_VERSION,'8.2.0','>=')],['PDO MySQL',extension_loaded('pdo_mysql')],['cURL',extension_loaded('curl')],['OpenSSL',extension_loaded('openssl')],['Fileinfo',extension_loaded('fileinfo')],['ZIP',extension_loaded('zip')],['GD',extension_loaded('gd')],['mbstring',extension_loaded('mbstring')],['storage writable',(is_dir($storage)||@mkdir($storage,0770,true))&&is_writable($storage)],['application folder writable',is_writable(__DIR__)]];}
function install_encrypt_ai(array $cfg,string $key): string {$plain=json_encode($cfg,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);$iv=random_bytes(12);$tag='';$cipher=openssl_encrypt($plain,'aes-256-gcm',hash('sha256',$key,true),OPENSSL_RAW_DATA,$iv,$tag);if($cipher===false)throw new RuntimeException('Could not encrypt AI settings.');return'enc:'.base64_encode($iv.$tag.$cipher);}

$env=env_read_simple(__DIR__.'/.env');$mode=(string)($env['APP_MODE']??(is_file(__DIR__.'/package-mode.php')?(require __DIR__.'/package-mode.php'):'hosted'));$offline=$mode==='offline';$checks=requirements();$requirementsOk=!in_array(false,array_column($checks,1),true);$step=(string)($_GET['step']??($offline?'company':'requirements'));$error='';$success=false;$installed=false;
if($env&&!empty($env['DB_DATABASE'])){try{$pdo=new PDO('mysql:host='.($env['DB_HOST']??'127.0.0.1').';port='.(int)($env['DB_PORT']??3306).';dbname='.$env['DB_DATABASE'].';charset=utf8mb4',$env['DB_USERNAME']??'root',$env['DB_PASSWORD']??'',[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);$installed=(bool)$pdo->query("SHOW TABLES LIKE 'users'")->fetchColumn()&&(int)$pdo->query('SELECT COUNT(*) FROM users')->fetchColumn()>0;}catch(Throwable){}}
if($installed){require __DIR__.'/bootstrap.php';if(!current_user()){header('Location:login.php');exit;}$success=true;}

if(!$installed&&($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
    $host=$offline?($env['DB_HOST']??'127.0.0.1'):trim((string)($_POST['db_host']??'127.0.0.1'));$port=$offline?(int)($env['DB_PORT']??3307):(int)($_POST['db_port']??3306);$database=$offline?($env['DB_DATABASE']??'crm_workspace'):trim((string)($_POST['db_name']??'crm_workspace'));$dbUser=$offline?($env['DB_USERNAME']??'root'):trim((string)($_POST['db_user']??'root'));$dbPass=$offline?($env['DB_PASSWORD']??''):(string)($_POST['db_pass']??'');
    $company=trim((string)($_POST['company_name']??''));$slug=trim((string)($_POST['company_slug']??'company'));$adminName=trim((string)($_POST['admin_name']??''));$adminEmail=trim((string)($_POST['admin_email']??''));$adminPass=(string)($_POST['admin_pass']??'');$provider=in_array((string)($_POST['ai_provider']??'off'),['off','local','cloud'],true)?(string)$_POST['ai_provider']:'off';$appKey=(string)($env['APP_KEY']??bin2hex(random_bytes(32)));
    try{
        if(!$requirementsOk)throw new RuntimeException('Server requirements are not satisfied.');if(!$company||!preg_match('/^[a-z0-9-]+$/',$slug)||!$adminName||!filter_var($adminEmail,FILTER_VALIDATE_EMAIL)||strlen($adminPass)<10)throw new RuntimeException('Complete all fields; password must contain at least 10 characters.');if(!preg_match('/^[A-Za-z0-9_]+$/',$database))throw new RuntimeException('Invalid database name.');
        $root=new PDO("mysql:host=$host;port=$port;charset=utf8mb4",$dbUser,$dbPass,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);$root->exec("CREATE DATABASE IF NOT EXISTS `$database` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");$pdo=new PDO("mysql:host=$host;port=$port;dbname=$database;charset=utf8mb4",$dbUser,$dbPass,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);migration_run($pdo,true);$pdo->beginTransaction();
        $pdo->prepare('INSERT INTO companies(name,slug,primary_color,accent_color) VALUES(?,?,?,?)')->execute([$company,$slug,'#173f35','#bd9856']);$cid=(int)$pdo->lastInsertId();$pdo->prepare('INSERT INTO users(company_id,name,email,password_hash,role,title,lang,active) VALUES(?,?,?,?,?,?,?,1)')->execute([$cid,$adminName,$adminEmail,password_hash($adminPass,defined('PASSWORD_ARGON2ID')?PASSWORD_ARGON2ID:PASSWORD_DEFAULT),'super_admin','System Administrator','fa']);$pdo->prepare('INSERT INTO app_settings(company_id,setting_key,setting_value) VALUES(?,?,?)')->execute([$cid,'currency','IRR']);
        $ai=['provider'=>$provider,'local_base_url'=>trim((string)($_POST['ai_local_url']??'http://127.0.0.1:11434/v1')),'local_model'=>trim((string)($_POST['ai_local_model']??'')),'cloud_base_url'=>trim((string)($_POST['ai_cloud_url']??'https://api.openai.com/v1')),'cloud_api_key'=>trim((string)($_POST['ai_cloud_key']??'')),'cloud_model'=>trim((string)($_POST['ai_cloud_model']??'')),'daily_company_limit'=>500,'daily_user_limit'=>50,'timeout'=>$provider==='local'?120:30,'features'=>['summarize'=>true,'draft_reply'=>true,'quote_read'=>true,'translate'=>true,'next_step'=>true],'input_cost_per_million'=>0,'output_cost_per_million'=>0];$pdo->prepare('INSERT INTO app_settings(company_id,setting_key,setting_value) VALUES(?,?,?)')->execute([$cid,'ai_config',install_encrypt_ai($ai,$appKey)]);$pdo->commit();
        foreach(['private_uploads','backups','imports','logs']as$name){$dir=__DIR__.'/storage/'.$name;if(!is_dir($dir))mkdir($dir,0770,true);}if(!$offline){$https=!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off';$base=($https?'https':'http').'://'.($_SERVER['HTTP_HOST']??'localhost').rtrim(dirname($_SERVER['SCRIPT_NAME']??''),'/\\');env_write(__DIR__.'/.env',['APP_MODE'=>'hosted','APP_ENV'=>'production','APP_NAME'=>APP_PRODUCT_NAME,'APP_URL'=>$base,'UPDATE_MANIFEST_URL'=>'https://makanlab.tech/downloads/update-manifest.json','APP_TIMEZONE'=>'Asia/Tehran','APP_KEY'=>$appKey,'CRON_KEY'=>bin2hex(random_bytes(24)),'REPAIR_KEY'=>bin2hex(random_bytes(24)),'SESSION_SECURE'=>$https?'true':'false','SESSION_NAME'=>APP_SESSION_NAME,'DB_HOST'=>$host,'DB_PORT'=>$port,'DB_DATABASE'=>$database,'DB_USERNAME'=>$dbUser,'DB_PASSWORD'=>$dbPass]);}migration_run($pdo);$success=true;
    }catch(Throwable$e){if(isset($pdo)&&$pdo->inTransaction())$pdo->rollBack();$error=$e->getMessage();}
}
?><!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=inst_e(APP_PRODUCT_NAME)?> Installer</title><link rel="stylesheet" href="assets/app.css?v=<?=APP_VERSION?>"><style>.install{max-width:900px;margin:35px auto}.req{display:flex;justify-content:space-between;padding:9px;border-bottom:1px solid #ddd}.pass{color:#176846}.fail{color:#a73333}</style></head><body><main class="panel install"><h1><?=inst_e(APP_PRODUCT_NAME)?> · <?=inst_e($mode)?></h1>
<?php if($success):?><div class="state success"><h2>نصب کامل شد / Installation complete</h2><a class="btn primary" href="login.php">ورود / Sign in</a></div>
<?php elseif($step==='requirements'):?><h2>بررسی نیازمندی‌ها / Requirements</h2><?php foreach($checks as[$label,$ok]):?><div class="req"><span><?=inst_e($label)?></span><b class="<?=$ok?'pass':'fail'?>"><?=$ok?'PASS ✓':'FAIL ✕'?></b></div><?php endforeach?><p>همه موارد باید PASS باشند. / All checks must pass before database setup.</p><?php if($requirementsOk):?><a class="btn primary" href="install.php?step=company">ادامه / Continue</a><?php endif?>
<?php else:?><?php if($error):?><div class="form-message error"><?=inst_e($error)?></div><?php endif?><form method="post" class="form-grid">
<?php if(!$offline):?><h3 class="full">Database</h3><?=fld('Host','db_host','127.0.0.1')?><?=fld('Port','db_port','3306','number')?><?=fld('Database','db_name','crm_workspace')?><?=fld('User','db_user','root')?><?=fld('Password','db_pass','','password',false)?><?php else:?><div class="full offline-banner">Database was configured automatically by the Windows installer.</div><?php endif?>
<h3 class="full">شرکت / Company</h3><?=fld('Company name','company_name','My Company')?><?=fld('Company code','company_slug','company')?><?=fld('Administrator name','admin_name','Administrator')?><?=fld('Administrator email','admin_email','','email')?><?=fld('Password (10+ characters)','admin_pass','','password')?>
<h3 class="full">هوش مصنوعی (اختیاری) / Optional AI</h3><label class="field"><span>Provider</span><select name="ai_provider"><option value="off" selected>Off (default)</option><option value="local">Local model (Ollama)</option><option value="cloud">Cloud API</option></select></label><?=fld('Ollama base URL','ai_local_url','http://127.0.0.1:11434/v1','url',false)?><?=fld('Ollama model','ai_local_model','','text',false)?><?=fld('Cloud base URL','ai_cloud_url','https://api.openai.com/v1','url',false)?><?=fld('Cloud API key','ai_cloud_key','','password',false)?><?=fld('Cloud model','ai_cloud_model','','text',false)?><p class="full">AI stays off unless selected. Change it later in Settings &gt; AI.</p><button class="btn primary full">نصب / Install</button></form><?php endif?><footer class="app-credit"><?=app_credit_html()?></footer></main></body></html>
