param([Parameter(Mandatory=$true)][string]$Root,[int]$WebPort=8088,[int]$DbPort=3307,[string]$BackupDir='',[switch]$Firewall)
$ErrorActionPreference='Stop';$app=Join-Path $Root 'app';$runtime=Join-Path $Root 'runtime';$data=Join-Path $Root 'data';$dbData=Join-Path $data 'mariadb\data';New-Item -ItemType Directory -Force -Path $data,$dbData,(Join-Path $app 'storage') | Out-Null
if(-not$BackupDir){$BackupDir=Join-Path $data 'backups'};New-Item -ItemType Directory -Force -Path $BackupDir | Out-Null
$phpDir=Join-Path $runtime 'php';$ini=Get-Content (Join-Path $phpDir 'php.ini-production') -Raw;$ini=$ini -replace ';extension_dir = "ext"','extension_dir = "ext"';foreach($e in 'curl','fileinfo','gd','mbstring','mysqli','openssl','pdo_mysql','zip','intl'){ $ini=$ini -replace ";extension=$e", "extension=$e" };$ini+="`ndate.timezone=Asia/Tehran`n";Set-Content -LiteralPath (Join-Path $phpDir 'php.ini') -Value $ini -Encoding ASCII
$myIni="[mysqld]`nbasedir=$($runtime.Replace('\','/'))/mariadb`ndatadir=$($dbData.Replace('\','/'))`nport=$DbPort`nbind-address=127.0.0.1`ncharacter-set-server=utf8mb4`ncollation-server=utf8mb4_unicode_ci`n[client]`nport=$DbPort`n";New-Item -ItemType Directory -Force -Path (Split-Path (Join-Path $data 'mariadb\my.ini'))|Out-Null;Set-Content -LiteralPath (Join-Path $data 'mariadb\my.ini') -Value $myIni -Encoding ASCII
$envFile=Join-Path $app '.env';if(-not(Test-Path $envFile)){$pass=[Convert]::ToHexString((1..24|ForEach-Object{Get-Random -Maximum 256}));$key=[Convert]::ToHexString((1..32|ForEach-Object{Get-Random -Maximum 256}));$cron=[Convert]::ToHexString((1..24|ForEach-Object{Get-Random -Maximum 256}));$mysqld=Join-Path $runtime 'mariadb\bin\mysqld.exe';&$mysqld --defaults-file="$data\mariadb\my.ini" --initialize-insecure;Start-Process $mysqld -ArgumentList "--defaults-file=`"$data\mariadb\my.ini`"" -WindowStyle Hidden;Start-Sleep -Seconds 8;$mysql=Join-Path $runtime 'mariadb\bin\mysql.exe';&$mysql --protocol=tcp -h127.0.0.1 -P$DbPort -uroot -e "ALTER USER 'root'@'localhost' IDENTIFIED BY '$pass'; CREATE DATABASE IF NOT EXISTS crm_workspace CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;";$content=@("APP_MODE=offline","APP_ENV=production","APP_NAME=CRM Workspace","APP_URL=http://localhost:$WebPort","APP_TIMEZONE=Asia/Tehran","APP_KEY=$key","CRON_KEY=$cron","REPAIR_KEY=$cron","SESSION_SECURE=false","SESSION_NAME=CRMWORKSPACESESSID","DB_HOST=127.0.0.1","DB_PORT=$DbPort","DB_DATABASE=crm_workspace","DB_USERNAME=root","DB_PASSWORD=$pass","BACKUP_DIR=$BackupDir");Set-Content -LiteralPath $envFile -Value $content -Encoding UTF8}
$caddy=":$WebPort {`n root * `"$($app.Replace('\','/'))`"`n php_fastcgi 127.0.0.1:9000`n file_server`n encode gzip`n}`n";Set-Content -LiteralPath (Join-Path $data 'Caddyfile') -Value $caddy -Encoding UTF8
$start=Join-Path $Root 'installer\offline-start.ps1';&powershell.exe -NoProfile -ExecutionPolicy Bypass -File $start -Root $Root;Start-Sleep -Seconds 5
$php=Join-Path $runtime 'php\php.exe';&$php (Join-Path $app 'migration-cli.php')
$taskStart="powershell.exe -NoProfile -WindowStyle Hidden -ExecutionPolicy Bypass -File `"$start`" -Root `"$Root`"";schtasks /Create /F /SC ONSTART /RU SYSTEM /RL HIGHEST /TN 'CRM Workspace Start' /TR $taskStart | Out-Null
schtasks /Create /F /SC MINUTE /MO 5 /RU SYSTEM /RL HIGHEST /TN 'CRM Workspace Cron' /TR "`"$php`" `"$app\cron-v10.php`"" | Out-Null
schtasks /Create /F /SC DAILY /ST 02:00 /RU SYSTEM /RL HIGHEST /TN 'CRM Workspace Daily Backup' /TR "`"$php`" `"$app\offline-backup.php`"" | Out-Null
if($Firewall){netsh advfirewall firewall add rule name='CRM Workspace LAN' dir=in action=allow protocol=TCP localport=$WebPort profile=private | Out-Null}
Start-Process "http://localhost:$WebPort/install.php?step=company"
