<?php
declare(strict_types=1);
require dirname(__DIR__).'/automation-engine.php';
$u=require_login();$cid=(int)$u['company_id'];$pdo=db();$method=$_SERVER['REQUEST_METHOD']??'GET';if($method!=='GET')verify_csrf();$action=(string)($_GET['action']??'users');
function admin_role_allowed(string $role): bool{return in_array($role,['super_admin','company_admin','manager','sales','project_manager','technical','finance','employee','viewer'],true);}
function admin_only(array $u): void{if(!in_array($u['role'],['company_admin','super_admin'],true))json_response(['ok'=>false,'error'=>'forbidden'],403);}
function admin_count(PDO $pdo,int $cid): int{$st=$pdo->prepare("SELECT COUNT(*) FROM users WHERE company_id=? AND active=1 AND role IN ('company_admin','super_admin')");$st->execute([$cid]);return(int)$st->fetchColumn();}
function admin_restore_order(PDO $pdo,array $tables): array {
 $tables=array_values(array_unique(array_filter($tables,fn($table)=>is_string($table)&&preg_match('/^[A-Za-z0-9_]+$/',$table))));$known=array_fill_keys($tables,true);$deps=array_fill_keys($tables,[]);
 $sql="SELECT table_name,referenced_table_name FROM information_schema.key_column_usage WHERE table_schema=DATABASE() AND referenced_table_name IS NOT NULL";
 foreach($pdo->query($sql) as $fk){$table=(string)$fk['table_name'];$parent=(string)$fk['referenced_table_name'];if($table!==$parent&&isset($known[$table],$known[$parent]))$deps[$table][$parent]=true;}
 $ordered=[];$remaining=$known;while($remaining){$ready=[];foreach(array_keys($remaining) as $table){if(!array_intersect_key($deps[$table],$remaining))$ready[]=$table;}if(!$ready){$ready=array_keys($remaining);}sort($ready,SORT_STRING);foreach($ready as $table){$ordered[]=$table;unset($remaining[$table]);}}
 return $ordered;
}
try{switch($action){
case 'users':require_cap_v10('admin.users.read');$st=$pdo->prepare('SELECT id,name,email,phone,extension,role,title,lang,active,last_login_at,created_at FROM users WHERE company_id=? ORDER BY active DESC,name');$st->execute([$cid]);json_response(['ok'=>true,'items'=>$st->fetchAll()]);
case 'save_user':
 admin_only($u);$b=body_json();$id=(int)req($b,'id',0);$name=trim((string)req($b,'name',''));$email=trim((string)req($b,'email',''));$role=(string)req($b,'role','employee');$active=!empty($b['active'])?1:0;if(!$name||!filter_var($email,FILTER_VALIDATE_EMAIL)||!admin_role_allowed($role))json_response(['ok'=>false,'error'=>'invalid_user'],422);
 if($id){$st=$pdo->prepare('SELECT role FROM users WHERE id=? AND company_id=?');$st->execute([$id,$cid]);$old=$st->fetchColumn();if($old===false)json_response(['ok'=>false,'error'=>'not_found'],404);if($id===(int)$u['id']&&$role!==$old)json_response(['ok'=>false,'error'=>'cannot_change_own_role'],422);if($id===(int)$u['id']&&!$active)json_response(['ok'=>false,'error'=>'cannot_deactivate_self'],422);if(in_array($old,['company_admin','super_admin'],true)&&(!in_array($role,['company_admin','super_admin'],true)||!$active)&&admin_count($pdo,$cid)<=1)json_response(['ok'=>false,'error'=>'cannot_deactivate_last_admin'],422);if($old==='super_admin')$role='super_admin';if($role==='super_admin'&&$old!=='super_admin'&&$u['role']!=='super_admin')json_response(['ok'=>false,'error'=>'forbidden'],403);$fields=['name=?','email=?','phone=?','extension=?','role=?','title=?','lang=?','active=?'];$args=[$name,$email,req($b,'phone'),req($b,'extension'),$role,req($b,'title'),clean_status((string)req($b,'lang','fa'),['fa','en'],'fa'),$active];$pass=(string)req($b,'password','');if($pass!==''){if(strlen($pass)<10)json_response(['ok'=>false,'error'=>'password_short'],422);$fields[]='password_hash=?';$args[]=hash_password($pass);}$args[]=$id;$args[]=$cid;$pdo->prepare('UPDATE users SET '.implode(',',$fields).' WHERE id=? AND company_id=?')->execute($args);}else{$pass=(string)req($b,'password','');if(strlen($pass)<10)json_response(['ok'=>false,'error'=>'password_short'],422);if($role==='super_admin'&&$u['role']!=='super_admin')json_response(['ok'=>false,'error'=>'forbidden'],403);$pdo->prepare('INSERT INTO users(company_id,name,email,phone,extension,password_hash,role,title,lang,active) VALUES(?,?,?,?,?,?,?,?,?,?)')->execute([$cid,$name,$email,req($b,'phone'),req($b,'extension'),hash_password($pass),$role,req($b,'title'),clean_status((string)req($b,'lang','fa'),['fa','en'],'fa'),$active]);$id=(int)$pdo->lastInsertId();}audit('save','user',$id,['role'=>$role]);json_response(['ok'=>true,'id'=>$id]);
case 'delete_user':admin_only($u);$b=body_json();$id=(int)req($b,'id',0);if($id===(int)$u['id'])json_response(['ok'=>false,'error'=>'cannot_deactivate_self'],422);$st=$pdo->prepare('SELECT role FROM users WHERE id=? AND company_id=? AND active=1');$st->execute([$id,$cid]);$role=$st->fetchColumn();if($role===false)json_response(['ok'=>false,'error'=>'not_found'],404);if(in_array($role,['company_admin','super_admin'],true)&&admin_count($pdo,$cid)<=1)json_response(['ok'=>false,'error'=>'cannot_deactivate_last_admin'],422);$pdo->prepare('UPDATE users SET active=0 WHERE id=? AND company_id=?')->execute([$id,$cid]);json_response(['ok'=>true]);
case 'change_password':$b=body_json();$current=(string)req($b,'current_password','');$new=(string)req($b,'new_password','');if(strlen($new)<10)json_response(['ok'=>false,'error'=>'password_short'],422);$st=$pdo->prepare('SELECT password_hash FROM users WHERE id=? AND company_id=?');$st->execute([$u['id'],$cid]);$hash=(string)$st->fetchColumn();if(!$hash||!password_verify($current,$hash))json_response(['ok'=>false,'error'=>'current_password_invalid'],422);$pdo->prepare('UPDATE users SET password_hash=? WHERE id=? AND company_id=?')->execute([hash_password($new),$u['id'],$cid]);json_response(['ok'=>true]);
case 'send_reset':admin_only($u);$b=body_json();$id=(int)req($b,'user_id',0);$st=$pdo->prepare('SELECT id,email FROM users WHERE id=? AND company_id=? AND active=1');$st->execute([$id,$cid]);$target=$st->fetch();if(!$target)json_response(['ok'=>false,'error'=>'not_found'],404);$token=v10_generate_token(32);$pdo->prepare('INSERT INTO v10_password_resets(company_id,user_id,token_hash,expires_at) VALUES(?,?,?,DATE_ADD(NOW(),INTERVAL 1 HOUR))')->execute([$cid,$id,hash('sha256',$token)]);$cfg=integration_settings($cid,'email');if(!$cfg['enabled'])json_response(['ok'=>false,'error'=>'email_not_configured'],422);$url=rtrim((string)envv('APP_URL',''),'/').'/reset-password.php?token='.rawurlencode($token);[$ok,$msg]=smtp_send($cfg['settings'],$target['email'],'Password reset','<p><a href="'.e($url).'">Reset password</a></p>');json_response(['ok'=>$ok,'message'=>$msg],$ok?200:502);
case 'branding':require_cap_v10('admin.settings.read');$st=$pdo->prepare('SELECT name,slug,logo_url,primary_color,accent_color FROM companies WHERE id=?');$st->execute([$cid]);json_response(['ok'=>true,'company'=>$st->fetch(),'base_currency'=>v10_company_setting($cid,'currency','IRR'),'fx_provider_url'=>v10_company_setting($cid,'fx_provider_url',''),'update_manifest_url'=>v10_company_setting($cid,'update_manifest_url',''),'sla_policies'=>json_decode((string)v10_company_setting($cid,'sla_policies','{}'),true)]);
case 'save_branding':require_cap_v10('admin.settings.write');$b=body_json();$name=trim((string)req($b,'name',''));$primary=(string)req($b,'primary_color','#173f35');$accent=(string)req($b,'accent_color','#bd9856');if(!$name)json_response(['ok'=>false,'error'=>'name_required'],422);if(!preg_match('/^#[0-9A-Fa-f]{6}$/',$primary)||!preg_match('/^#[0-9A-Fa-f]{6}$/',$accent))json_response(['ok'=>false,'error'=>'invalid_color'],422);$pdo->prepare('UPDATE companies SET name=?,logo_url=?,primary_color=?,accent_color=? WHERE id=?')->execute([$name,req($b,'logo_url'),$primary,$accent,$cid]);v10_set_company_setting($cid,'currency',strtoupper((string)req($b,'base_currency','IRR')));v10_set_company_setting($cid,'fx_provider_url',trim((string)req($b,'fx_provider_url','')));v10_set_company_setting($cid,'update_manifest_url',trim((string)req($b,'update_manifest_url','')));$sla=[];foreach(['low','medium','high','urgent'] as $p)$sla[$p]=max(1,(int)req($b,'sla_'.$p,24));v10_set_company_setting($cid,'sla_policies',json_encode($sla));json_response(['ok'=>true]);
case 'custom_fields':require_cap_v10('admin.settings.read');$st=$pdo->prepare('SELECT * FROM custom_fields WHERE company_id=? ORDER BY entity_type,position,id');$st->execute([$cid]);json_response(['ok'=>true,'items'=>$st->fetchAll()]);
case 'save_custom_field':require_cap_v10('admin.settings.write');$b=body_json();$id=(int)req($b,'id',0);$entity=preg_replace('/[^a-z_]/','',(string)req($b,'entity_type','customers'));$key=preg_replace('/[^a-z0-9_]/','_',strtolower((string)req($b,'field_key','')));$type=clean_status((string)req($b,'field_type','text'),['text','textarea','number','date','select','checkbox'],'text');if(!$key||!$entity)json_response(['ok'=>false,'error'=>'invalid_field'],422);$vals=[$entity,$key,trim((string)req($b,'label_fa',$key)),trim((string)req($b,'label_en',$key)),$type,json_encode(array_values(array_filter(array_map('trim',explode(',',(string)req($b,'options','')))))),!empty($b['required'])?1:0,!empty($b['active'])?1:0,(int)req($b,'position',0)];if($id)$pdo->prepare('UPDATE custom_fields SET entity_type=?,field_key=?,label_fa=?,label_en=?,field_type=?,options_json=?,required=?,active=?,position=? WHERE id=? AND company_id=?')->execute([...$vals,$id,$cid]);else{$pdo->prepare('INSERT INTO custom_fields(company_id,entity_type,field_key,label_fa,label_en,field_type,options_json,required,active,position) VALUES(?,?,?,?,?,?,?,?,?,?)')->execute([$cid,...$vals]);$id=(int)$pdo->lastInsertId();}json_response(['ok'=>true,'id'=>$id]);
case 'delete_custom_field':require_cap_v10('admin.settings.write');$b=body_json();$pdo->prepare('DELETE FROM custom_fields WHERE id=? AND company_id=?')->execute([(int)req($b,'id',0),$cid]);json_response(['ok'=>true]);
case 'audit':require_cap_v10('admin.settings.read');$st=$pdo->prepare('SELECT a.*,u.name user_name FROM activity_logs a LEFT JOIN users u ON u.id=a.user_id WHERE a.company_id=? ORDER BY a.created_at DESC LIMIT 500');$st->execute([$cid]);json_response(['ok'=>true,'items'=>$st->fetchAll()]);
case 'onboarding':
 $checks=[];foreach(['add_customer_done'=>'customers','add_deal_done'=>'opportunities'] as $key=>$table){$st=$pdo->prepare('SELECT EXISTS(SELECT 1 FROM `'.$table.'` WHERE company_id=?)');$st->execute([$cid]);$checks[$key]=(int)$st->fetchColumn();}$st=$pdo->prepare('SELECT COUNT(*)>1 FROM users WHERE company_id=? AND active=1');$st->execute([$cid]);$checks['invite_user_done']=(int)$st->fetchColumn();$pdo->prepare('INSERT INTO v10_onboarding(company_id,user_id,add_customer_done,add_deal_done,invite_user_done) VALUES(?,?,?,?,?) ON DUPLICATE KEY UPDATE add_customer_done=VALUES(add_customer_done),add_deal_done=VALUES(add_deal_done),invite_user_done=VALUES(invite_user_done)')->execute([$cid,$u['id'],$checks['add_customer_done'],$checks['add_deal_done'],$checks['invite_user_done']]);$st=$pdo->prepare('SELECT * FROM v10_onboarding WHERE company_id=? AND user_id=?');$st->execute([$cid,$u['id']]);json_response(['ok'=>true,'state'=>$st->fetch()]);
case 'dismiss_onboarding':$pdo->prepare('INSERT INTO v10_onboarding(company_id,user_id,dismissed) VALUES(?,?,1) ON DUPLICATE KEY UPDATE dismissed=1')->execute([$cid,$u['id']]);json_response(['ok'=>true]);
case 'load_sample':
 require_cap_v10('admin.settings.write');$st=$pdo->prepare("SELECT id FROM customers WHERE company_id=? AND name='Sample Customer' LIMIT 1");$st->execute([$cid]);if($st->fetchColumn())json_response(['ok'=>true,'already_loaded'=>true]);$pdo->beginTransaction();try{$pdo->prepare("INSERT INTO customers(company_id,name,email,phone,city,status,owner_id,notes) VALUES(?,?,?,?,?,'active',?,'Sample data')")->execute([$cid,'Sample Customer','sample@example.com','+98 21 0000 0000','Tehran',$u['id']]);$customer=(int)$pdo->lastInsertId();$pdo->prepare("INSERT INTO opportunities(company_id,customer_id,title,stage,amount,currency,probability,expected_close_date,owner_id,notes) VALUES(?,?,?,'qualified',250000,'USD',40,DATE_ADD(CURDATE(),INTERVAL 30 DAY),?,'Sample data')")->execute([$cid,$customer,'Sample opportunity',$u['id']]);$pdo->commit();json_response(['ok'=>true]);}catch(Throwable $e){$pdo->rollBack();throw$e;}
case 'trash':require_cap_v10('trash.manage');$st=$pdo->prepare('SELECT d.*,u.name deleted_by_name FROM v10_record_deletions d LEFT JOIN users u ON u.id=d.deleted_by WHERE d.company_id=? ORDER BY d.deleted_at DESC');$st->execute([$cid]);$items=$st->fetchAll();foreach($items as &$item){try{$m=v10_meta((string)$item['entity_type']);$q=$pdo->prepare('SELECT '.v10_identifier($m['title']).' FROM `'.$m['table'].'` WHERE company_id=? AND id=?');$q->execute([$cid,$item['entity_id']]);$item['record_title']=$q->fetchColumn()?:null;}catch(Throwable $ignore){$item['record_title']=null;}}json_response(['ok'=>true,'items'=>$items]);
case 'restore':require_cap_v10('trash.manage');$b=body_json();v10_restore((string)req($b,'entity_type',''),(int)req($b,'entity_id',0),$u);json_response(['ok'=>true]);
case 'api_tokens':require_cap_v10('admin.settings.read');$st=$pdo->prepare('SELECT id,name,LEFT(token_hash,10) token_prefix,scopes,expires_at,last_used_at,created_at,revoked_at FROM api_tokens WHERE company_id=? ORDER BY created_at DESC');$st->execute([$cid]);json_response(['ok'=>true,'items'=>$st->fetchAll()]);
case 'api_token_create':require_cap_v10('admin.settings.write');$b=body_json();$name=trim((string)req($b,'name','API token'));$token=v10_generate_token(36);$scopes=trim((string)req($b,'scopes','*'));$expires=req($b,'expires_at')?:null;$pdo->prepare('INSERT INTO api_tokens(company_id,user_id,name,token_hash,scopes,expires_at) VALUES(?,?,?,?,?,?)')->execute([$cid,$u['id'],$name,hash('sha256',$token),json_encode(array_values(array_filter(array_map('trim',explode(',',$scopes))))),$expires]);json_response(['ok'=>true,'id'=>(int)$pdo->lastInsertId(),'token'=>$token]);
case 'api_token_revoke':require_cap_v10('admin.settings.write');$b=body_json();$pdo->prepare('UPDATE api_tokens SET revoked_at=NOW() WHERE id=? AND company_id=?')->execute([(int)req($b,'id',0),$cid]);json_response(['ok'=>true]);
case 'backup_list':require_cap_v10('admin.settings.read');$st=$pdo->prepare('SELECT * FROM v10_backups WHERE company_id=? ORDER BY created_at DESC');$st->execute([$cid]);json_response(['ok'=>true,'items'=>$st->fetchAll()]);
case 'backup_create':
 require_cap_v10('admin.settings.write');if(!class_exists('ZipArchive'))json_response(['ok'=>false,'error'=>'zip_extension_required'],500);$dir=v10_storage_dir('backups');$name='backup-'.$cid.'-'.date('Ymd-His').'.zip';$path=$dir.'/'.$name;$tables=$pdo->query("SELECT table_name FROM information_schema.columns WHERE table_schema=DATABASE() AND column_name='company_id' ORDER BY table_name")->fetchAll(PDO::FETCH_COLUMN);$dump=['version'=>APP_VERSION,'company_id'=>$cid,'created_at'=>date(DATE_ATOM),'tables'=>[]];$st=$pdo->prepare('SELECT * FROM companies WHERE id=?');$st->execute([$cid]);$dump['tables']['companies']=$st->fetchAll();foreach($tables as $table){if(!preg_match('/^[A-Za-z0-9_]+$/',$table))continue;$st=$pdo->prepare('SELECT * FROM `'.$table.'` WHERE company_id=?');$st->execute([$cid]);$dump['tables'][$table]=$st->fetchAll();}$zip=new ZipArchive();if($zip->open($path,ZipArchive::CREATE|ZipArchive::OVERWRITE)!==true)json_response(['ok'=>false,'error'=>'backup_not_writable'],500);$zip->addFromString('database.json',json_encode($dump,JSON_UNESCAPED_UNICODE|JSON_PRETTY_PRINT));$uploads=v10_storage_dir('private_uploads').'/'.$cid;if(is_dir($uploads)){$it=new RecursiveIteratorIterator(new RecursiveDirectoryIterator($uploads,FilesystemIterator::SKIP_DOTS));foreach($it as $file)if($file->isFile())$zip->addFile($file->getPathname(),'uploads/'.substr($file->getPathname(),strlen($uploads)+1));}$zip->close();$size=filesize($path)?:0;$pdo->prepare('INSERT INTO v10_backups(company_id,file_name,file_size,created_by) VALUES(?,?,?,?)')->execute([$cid,$name,$size,$u['id']]);json_response(['ok'=>true,'file'=>$name,'size'=>$size]);
case 'backup_download':require_cap_v10('admin.settings.read');$id=(int)($_GET['id']??0);$st=$pdo->prepare('SELECT file_name FROM v10_backups WHERE id=? AND company_id=?');$st->execute([$id,$cid]);$file=(string)$st->fetchColumn();$path=v10_storage_dir('backups').'/'.basename($file);if(!$file||!is_file($path)){http_response_code(404);exit('Not found');}header('Content-Type: application/zip');header('Content-Disposition: attachment; filename="'.basename($file).'"');header('Content-Length: '.filesize($path));readfile($path);exit;
case 'backup_delete':require_cap_v10('admin.settings.write');$b=body_json();$id=(int)req($b,'id',0);$st=$pdo->prepare('SELECT file_name FROM v10_backups WHERE id=? AND company_id=?');$st->execute([$id,$cid]);$file=(string)$st->fetchColumn();if($file){@unlink(v10_storage_dir('backups').'/'.basename($file));$pdo->prepare('DELETE FROM v10_backups WHERE id=? AND company_id=?')->execute([$id,$cid]);}json_response(['ok'=>true]);
case 'backup_restore':
 require_cap_v10('admin.settings.write');$b=body_json();$id=(int)req($b,'id',0);$st=$pdo->prepare('SELECT file_name FROM v10_backups WHERE id=? AND company_id=?');$st->execute([$id,$cid]);$file=(string)$st->fetchColumn();if(!$file||!hash_equals($file,(string)req($b,'confirmation','')))json_response(['ok'=>false,'error'=>'confirmation_mismatch'],422);$path=v10_storage_dir('backups').'/'.basename($file);$zip=new ZipArchive();if(!is_file($path)||$zip->open($path)!==true)json_response(['ok'=>false,'error'=>'backup_not_found'],404);$dump=json_decode((string)$zip->getFromName('database.json'),true);if(!is_array($dump)||($dump['company_id']??null)!=$cid)json_response(['ok'=>false,'error'=>'invalid_backup'],422);$tables=admin_restore_order($pdo,array_keys((array)$dump['tables']));$pdo->beginTransaction();try{foreach($tables as $table){if(!v10_table_exists($table))continue;foreach((array)$dump['tables'][$table] as $row){if(!is_array($row)||($table==='companies'?(int)($row['id']??0)!==$cid:(int)($row['company_id']??0)!==$cid))continue;$cols=array_keys($row);$updates=array_map(fn($col)=>v10_identifier($col).'=VALUES('.v10_identifier($col).')',$cols);$pdo->prepare('INSERT INTO `'.$table.'` ('.implode(',',array_map('v10_identifier',$cols)).') VALUES('.implode(',',array_fill(0,count($cols),'?')).') ON DUPLICATE KEY UPDATE '.implode(',',$updates))->execute(array_values($row));}}$uploadDir=v10_storage_dir('private_uploads').'/'.$cid;if(!is_dir($uploadDir)&&!mkdir($uploadDir,0700,true))throw new RuntimeException('Upload storage not writable');if(!is_writable($uploadDir))throw new RuntimeException('Upload storage not writable');for($i=0;$i<$zip->numFiles;$i++){$entry=$zip->getNameIndex($i);if(!str_starts_with($entry,'uploads/')||str_ends_with($entry,'/'))continue;$relative=substr($entry,8);if($relative===''||str_contains($relative,'..')||str_contains($relative,'\\'))continue;$dest=$uploadDir.'/'.$relative;if(!is_dir(dirname($dest))&&!mkdir(dirname($dest),0700,true))throw new RuntimeException('Upload storage not writable');$in=$zip->getStream($entry);$out=fopen($dest,'wb');if(!$in||!$out)throw new RuntimeException('Upload restore failed');stream_copy_to_stream($in,$out);fclose($in);fclose($out);}$pdo->commit();$zip->close();json_response(['ok'=>true]);}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();$zip->close();throw$e;}
case 'update_apply':require_cap_v10('admin.settings.write');require_once dirname(__DIR__).'/update-manager.php';$url=trim((string)v10_company_setting($cid,'update_manifest_url',(string)envv('UPDATE_MANIFEST_URL','')));if($url==='')json_response(['ok'=>false,'error'=>'not_configured'],422);json_response(['ok'=>true,'result'=>app_apply_update($url)]);
case 'update_check':
 require_cap_v10('admin.settings.read');$url=trim((string)v10_company_setting($cid,'update_manifest_url',(string)envv('UPDATE_MANIFEST_URL','')));$status='not_configured';$latest=null;$manifest=null;if($url!==''){$ctx=stream_context_create(['http'=>['timeout'=>5,'ignore_errors'=>true],'https'=>['timeout'=>5,'ignore_errors'=>true]]);$raw=@file_get_contents($url,false,$ctx);$manifest=is_string($raw)?json_decode($raw,true):null;if(is_array($manifest)&&!empty($manifest['version'])){$latest=(string)$manifest['version'];$status=version_compare($latest,APP_VERSION,'>')?'available':'current';}else{$status='unavailable';}}$pdo->prepare('INSERT INTO v10_update_checks(company_id,current_version,latest_version,manifest_url,status,checked_by) VALUES(?,?,?,?,?,?)')->execute([$cid,APP_VERSION,$latest,$url?:null,$status,$u['id']]);json_response(['ok'=>true,'status'=>$status,'current'=>APP_VERSION,'latest'=>$latest,'manifest'=>$manifest]);
default:json_response(['ok'=>false,'error'=>'unknown_action'],404);
}}catch(Throwable $e){error_log($e->__toString());json_response(['ok'=>false,'error'=>'server_error','message'=>envv('APP_ENV','local')==='local'?$e->getMessage():'Internal server error'],500);}
