<?php
declare(strict_types=1);
require dirname(__DIR__).'/ai-lib.php';
$u=require_login();$cid=(int)$u['company_id'];$uid=(int)$u['id'];$action=(string)($_GET['action']??'settings');$method=(string)($_SERVER['REQUEST_METHOD']??'GET');if($method!=='GET')verify_csrf();
try{
 switch($action){
  case 'availability':$cfg=ai_settings($cid);json_response(['ok'=>true,'enabled'=>$cfg['provider']!=='off','provider'=>$cfg['provider'],'features'=>$cfg['features']]);
  case 'settings':require_cap_v10('admin.settings.read');json_response(['ok'=>true,'settings'=>ai_public_settings(ai_settings($cid))]);
  case 'save_settings':require_cap_v10('admin.settings.write');$cfg=ai_save_settings($cid,body_json());audit('save','ai_settings',null,['provider'=>$cfg['provider']]);json_response(['ok'=>true,'settings'=>ai_public_settings($cfg)]);
  case 'models':require_cap_v10('admin.settings.read');$cfg=ai_settings($cid);if($cfg['provider']!=='local')json_response(['ok'=>false,'error'=>'local_provider_required'],422);json_response(['ok'=>true,'items'=>ai_list_models($cfg)]);
  case 'test':require_cap_v10('admin.settings.read');$cfg=ai_settings($cid);$r=ai_call($cfg,'test',['message'=>'connection test'],$u['lang']??'en',$cid,$uid);json_response(['ok'=>true,'message'=>$r['content']]);
  case 'usage':require_cap_v10('admin.settings.read');$cfg=ai_settings($cid);$st=db()->prepare('SELECT DATE(a.created_at) usage_date,a.user_id,u.name user_name,COUNT(*) calls,SUM(a.success) successes,SUM(a.tokens_in) tokens_in,SUM(a.tokens_out) tokens_out,ROUND(SUM(a.tokens_in)*?/1000000+SUM(a.tokens_out)*?/1000000,6) estimated_cost FROM v10_ai_calls a LEFT JOIN users u ON u.id=a.user_id WHERE a.company_id=? GROUP BY DATE(a.created_at),a.user_id,u.name ORDER BY usage_date DESC,user_name LIMIT 1000');$st->execute([(float)$cfg['input_cost_per_million'],(float)$cfg['output_cost_per_million'],$cid]);json_response(['ok'=>true,'items'=>$st->fetchAll()]);
  case 'call':
    $b=str_starts_with((string)($_SERVER['CONTENT_TYPE']??''),'multipart/form-data')?$_POST:body_json();$feature=clean_status((string)($b['feature']??''),['summarize','draft_reply','quote_read','translate','next_step'],'');if($feature==='')json_response(['ok'=>false,'error'=>'unknown_ai_feature'],422);$cfg=ai_settings($cid);if($cfg['provider']==='off')json_response(['ok'=>false,'error'=>'ai_off','message'=>'AI is turned off.'],422);if(empty($cfg['features'][$feature]))json_response(['ok'=>false,'error'=>'feature_disabled','message'=>'This AI feature is disabled.'],403);
    $entity=trim((string)($b['entity_type']??''));$entityId=(int)($b['entity_id']??0);$context=[];
    if(in_array($feature,['summarize','next_step'],true)){if(!$entity||!$entityId)json_response(['ok'=>false,'error'=>'record_required'],422);$context=ai_record_context($entity,$entityId,$cid,$u);if($feature==='summarize'&&!in_array($entity,['customers','opportunities','projects'],true))json_response(['ok'=>false,'error'=>'unsupported_record'],422);if($feature==='next_step'&&$entity!=='opportunities')json_response(['ok'=>false,'error'=>'unsupported_record'],422);if($feature==='next_step'&&strtotime((string)($context['last_activity_at']??'now'))>strtotime('-7 days'))json_response(['ok'=>false,'error'=>'deal_not_inactive','message'=>'This deal has activity within the last 7 days.'],422);}
    elseif($feature==='quote_read'){$entity='rfqs';if(!$entityId)json_response(['ok'=>false,'error'=>'record_required'],422);$context=ai_record_context('rfqs',$entityId,$cid,$u);$text=trim((string)($b['text']??''));if(isset($_FILES['pdf'])&&is_uploaded_file($_FILES['pdf']['tmp_name'])){if((int)$_FILES['pdf']['size']>10*1024*1024)json_response(['ok'=>false,'error'=>'file_too_large'],413);$mime=(new finfo(FILEINFO_MIME_TYPE))->file($_FILES['pdf']['tmp_name']);if($mime!=='application/pdf')json_response(['ok'=>false,'error'=>'pdf_required'],422);$autoload=dirname(__DIR__).'/vendor/autoload.php';if(is_file($autoload))require_once$autoload;if(!class_exists('Smalot\\PdfParser\\Parser'))json_response(['ok'=>false,'error'=>'pdf_parser_unavailable','message'=>'PDF text extraction is unavailable; paste the quotation text instead.'],422);$parser=new Smalot\PdfParser\Parser();$text=trim($parser->parseFile($_FILES['pdf']['tmp_name'])->getText());}if($text==='')json_response(['ok'=>false,'error'=>'quote_text_required'],422);$context=['rfq'=>$context['record'],'quotation_text'=>mb_substr($text,0,100000),'required_json'=>['supplier'=>'string','quote_ref'=>'string','items'=>[['description'=>'string','qty'=>'number','unit'=>'string','unit_price'=>'number','currency'=>'string','technical_match'=>'string']],'currency'=>'string','freight'=>'number','lead_time_days'=>'integer','payment_terms'=>'string','notes'=>'string']];}
    else{$text=trim((string)($b['text']??''));if($text==='')json_response(['ok'=>false,'error'=>'text_required'],422);$context=['text'=>mb_substr($text,0,50000)];if($feature==='draft_reply')$context['instruction']=mb_substr(trim((string)($b['instruction']??'')),0,500);if($entity&&$entityId)$context['record']=ai_record_context($entity,$entityId,$cid,$u);if($feature==='translate')$context['target_language']=(string)($b['target_language']??(($u['lang']??'fa')==='fa'?'en':'fa'));}
    $r=ai_call($cfg,$feature,$context,$u['lang']??'fa',$cid,$uid,$entity?:null,$entityId?:null,$feature==='quote_read');if($feature==='quote_read')json_response(['ok'=>true,'draft'=>$r['json']]);json_response(['ok'=>true,'draft'=>$r['content']]);
  default:json_response(['ok'=>false,'error'=>'unknown_action'],404);
 }
}catch(Throwable$e){error_log($e->__toString());$msg=$e->getMessage();json_response(['ok'=>false,'error'=>'ai_failed','message'=>$msg!==''?$msg:'AI request failed. The page remains usable.'],502);}
