<?php
declare(strict_types=1);
require dirname(__DIR__).'/automation-engine.php';
$u=require_login();$cid=(int)$u['company_id'];$pdo=db();$method=$_SERVER['REQUEST_METHOD']??'GET';if($method!=='GET')verify_csrf();$action=(string)($_GET['action']??'rules');
try{
 switch($action){
  case 'rules':require_cap_v10('automation.read');$st=$pdo->prepare('SELECT r.*,u.name created_by_name FROM v10_workflow_rules r LEFT JOIN users u ON u.id=r.created_by WHERE r.company_id=? ORDER BY r.updated_at DESC');$st->execute([$cid]);json_response(['ok'=>true,'items'=>$st->fetchAll()]);
  case 'save_rule':require_cap_v10('automation.write');$b=body_json();$id=(int)req($b,'id',0);$name=trim((string)req($b,'name',''));$entity=(string)req($b,'entity_type','');v10_meta($entity);$trigger=clean_status((string)req($b,'trigger_type','record_created'),['record_created','record_updated','stage_changed','field_changed','date_reached'],'record_created');$actionType=clean_status((string)req($b,'action_type','create_task'),['create_task','send_sms','send_email','notify_user','change_owner'],'create_task');if(!$name)json_response(['ok'=>false,'error'=>'name_required'],422);$cond=(array)req($b,'condition',[]);$act=(array)req($b,'action',[]);$vals=[$name,$entity,$trigger,req($b,'trigger_field')?:null,json_encode($cond,JSON_UNESCAPED_UNICODE),$actionType,json_encode($act,JSON_UNESCAPED_UNICODE),!empty($b['enabled'])?1:0];if($id){$st=$pdo->prepare('UPDATE v10_workflow_rules SET name=?,entity_type=?,trigger_type=?,trigger_field=?,condition_json=?,action_type=?,action_json=?,enabled=? WHERE id=? AND company_id=?');$st->execute([...$vals,$id,$cid]);}else{$st=$pdo->prepare('INSERT INTO v10_workflow_rules(company_id,name,entity_type,trigger_type,trigger_field,condition_json,action_type,action_json,enabled,created_by) VALUES(?,?,?,?,?,?,?,?,?,?)');$st->execute([$cid,...$vals,$u['id']]);$id=(int)$pdo->lastInsertId();}audit('save','workflow_rule',$id);json_response(['ok'=>true,'id'=>$id]);
  case 'delete_rule':require_cap_v10('automation.write');$b=body_json();$id=(int)req($b,'id',0);$pdo->prepare('DELETE FROM v10_workflow_rules WHERE id=? AND company_id=?')->execute([$id,$cid]);audit('delete','workflow_rule',$id);json_response(['ok'=>true]);
  case 'runs':require_cap_v10('automation.read');$st=$pdo->prepare('SELECT wr.*,r.name rule_name FROM v10_workflow_runs wr JOIN v10_workflow_rules r ON r.id=wr.rule_id WHERE wr.company_id=? ORDER BY wr.ran_at DESC LIMIT 300');$st->execute([$cid]);json_response(['ok'=>true,'items'=>$st->fetchAll()]);
  case 'reminders':require_cap_v10('crm.read');$all=can_v10('automation.read',$u);$sql='SELECT r.*,us.name user_name FROM reminders r JOIN users us ON us.id=r.user_id WHERE r.company_id=?'.($all?'':' AND r.user_id=?').' ORDER BY FIELD(r.status,\'pending\',\'snoozed\',\'sent\',\'cancelled\'),r.remind_at';$st=$pdo->prepare($sql);$st->execute($all?[$cid]:[$cid,$u['id']]);json_response(['ok'=>true,'items'=>$st->fetchAll()]);
  case 'save_reminder':require_cap_v10('crm.read');$b=body_json();$id=(int)req($b,'id',0);$uid=(int)req($b,'user_id',$u['id']);if($uid!== (int)$u['id']&&!can_v10('automation.write',$u))json_response(['ok'=>false,'error'=>'forbidden'],403);tenant_ref('users',$uid,$cid,true);$title=trim((string)req($b,'title',''));$at=trim((string)req($b,'remind_at',''));if(!$title||!$at)json_response(['ok'=>false,'error'=>'title_time_required'],422);$channels=implode(',',array_intersect((array)req($b,'channels',['in_app']),['in_app','email','sms']));$entity=(string)req($b,'entity_type','');$eid=(int)req($b,'entity_id',0)?:null;if($entity&&$eid)v10_require_record($entity,$eid,$cid);$vals=[$uid,$entity?:null,$eid,req($b,'source_key')?:null,$title,req($b,'message')?:null,$at,clean_status((string)req($b,'recurrence','none'),['none','daily','weekly','monthly'],'none'),$channels?:'in_app','pending'];if($id){$st=$pdo->prepare('SELECT user_id FROM reminders WHERE id=? AND company_id=?');$st->execute([$id,$cid]);$owner=(int)$st->fetchColumn();if(!$owner||($owner!==(int)$u['id']&&!can_v10('automation.write',$u)))json_response(['ok'=>false,'error'=>'forbidden'],403);$pdo->prepare('UPDATE reminders SET user_id=?,entity_type=?,entity_id=?,source_key=?,title=?,message=?,remind_at=?,recurrence=?,channels=?,status=? WHERE id=? AND company_id=?')->execute([...$vals,$id,$cid]);}else{$pdo->prepare('INSERT INTO reminders(company_id,user_id,entity_type,entity_id,source_key,title,message,remind_at,recurrence,channels,status,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)')->execute([$cid,...$vals,$u['id']]);$id=(int)$pdo->lastInsertId();}json_response(['ok'=>true,'id'=>$id]);
  case 'reminder_action':require_cap_v10('crm.read');$b=body_json();$id=(int)req($b,'id',0);$op=(string)req($b,'operation','cancel');$st=$pdo->prepare('SELECT user_id FROM reminders WHERE id=? AND company_id=?');$st->execute([$id,$cid]);$owner=(int)$st->fetchColumn();if(!$owner||($owner!==(int)$u['id']&&!can_v10('automation.write',$u)))json_response(['ok'=>false,'error'=>'forbidden'],403);if($op==='cancel')$pdo->prepare("UPDATE reminders SET status='cancelled' WHERE id=? AND company_id=?")->execute([$id,$cid]);elseif($op==='snooze'){$mins=max(5,min(10080,(int)req($b,'minutes',30)));$pdo->prepare("UPDATE reminders SET status='pending',remind_at=DATE_ADD(NOW(),INTERVAL ? MINUTE) WHERE id=? AND company_id=?")->execute([$mins,$id,$cid]);}else json_response(['ok'=>false,'error'=>'bad_operation'],422);json_response(['ok'=>true]);
  default:json_response(['ok'=>false,'error'=>'unknown_action'],404);
 }
}catch(Throwable $e){error_log($e->__toString());json_response(['ok'=>false,'error'=>'server_error','message'=>envv('APP_ENV','local')==='local'?$e->getMessage():'Internal server error'],500);}
