<?php
declare(strict_types=1);
require dirname(__DIR__).'/automation-engine.php';
$u=require_login();$cid=(int)$u['company_id'];$pdo=db();$method=$_SERVER['REQUEST_METHOD']??'GET';if($method!=='GET')verify_csrf();$action=(string)($_GET['action']??'logs');
try{
 switch($action){
  case 'logs':require_cap_v10('communications.read');$limit=min(300,max(20,(int)($_GET['limit']??100)));$st=$pdo->prepare('SELECT c.*,u.name user_name FROM communication_logs c LEFT JOIN users u ON u.id=c.user_id WHERE c.company_id=? ORDER BY c.created_at DESC LIMIT '.$limit);$st->execute([$cid]);json_response(['ok'=>true,'items'=>$st->fetchAll()]);
  case 'send':require_cap_v10('communications.write');$b=body_json();$channel=(string)req($b,'channel','email');$to=trim((string)req($b,'recipient',''));$subject=(string)req($b,'subject','CRM');$body=(string)req($b,'body','');$entity=(string)req($b,'entity_type','');$eid=(int)req($b,'entity_id',0)?:null;if($entity&&$eid)v10_require_record($entity,$eid,$cid);
    if($channel==='email'){$cfg=integration_settings($cid,'email');if(!$cfg['enabled'])json_response(['ok'=>false,'error'=>'email_not_configured'],422);[$ok,$msg]=smtp_send($cfg['settings'],$to,$subject,nl2br(e($body)));log_communication($cid,(int)$u['id'],'email',$to,$subject,$body,$ok?'sent':'failed',$cfg['provider'],$ok?'':$msg);if($entity&&$eid)v10_timeline($entity,$eid,'email',$subject,$body,'communication',null,(int)$u['id'],['status'=>$ok?'sent':'failed','recipient'=>$to]);json_response(['ok'=>$ok,'message'=>$msg],$ok?200:502);}
    if($channel==='sms'){$cfg=integration_settings($cid,'sms');if(!$cfg['enabled'])json_response(['ok'=>false,'error'=>'sms_not_configured'],422);[$ok,$msg]=sms_send_v10($cfg['provider'],$cfg['settings'],$to,$body);log_communication($cid,(int)$u['id'],'sms',$to,$subject,$body,$ok?'sent':'failed',$cfg['provider'],$ok?'':$msg);if($entity&&$eid)v10_timeline($entity,$eid,'sms',$subject,$body,'communication',null,(int)$u['id'],['status'=>$ok?'sent':'failed','recipient'=>$to]);json_response(['ok'=>$ok,'message'=>$msg],$ok?200:502);}
    json_response(['ok'=>false,'error'=>'bad_channel'],422);
  case 'templates':require_cap_v10('communications.read');$st=$pdo->prepare('SELECT * FROM v10_message_templates WHERE company_id=? ORDER BY channel,name');$st->execute([$cid]);json_response(['ok'=>true,'items'=>$st->fetchAll()]);
  case 'save_template':require_cap_v10('communications.write');$b=body_json();$id=(int)req($b,'id',0);$channel=clean_status((string)req($b,'channel','email'),['email','sms'],'email');$name=trim((string)req($b,'name',''));$body=trim((string)req($b,'body',''));if(!$name||!$body)json_response(['ok'=>false,'error'=>'required'],422);if($id)$pdo->prepare('UPDATE v10_message_templates SET channel=?,name=?,subject=?,body=? WHERE id=? AND company_id=?')->execute([$channel,$name,req($b,'subject'),$body,$id,$cid]);else{$pdo->prepare('INSERT INTO v10_message_templates(company_id,channel,name,subject,body,created_by) VALUES(?,?,?,?,?,?)')->execute([$cid,$channel,$name,req($b,'subject'),$body,$u['id']]);$id=(int)$pdo->lastInsertId();}json_response(['ok'=>true,'id'=>$id]);
  case 'delete_template':require_cap_v10('communications.write');$b=body_json();$pdo->prepare('DELETE FROM v10_message_templates WHERE id=? AND company_id=?')->execute([(int)req($b,'id',0),$cid]);json_response(['ok'=>true]);
  case 'sync_imap':require_cap_v10('communications.write');[$ok,$message,$added]=imap_sync_v10($cid);json_response(['ok'=>$ok,'added'=>$added,'message'=>$message],$ok?200:502);
  case 'incoming_calls':require_cap_v10('communications.read');$after=max(0,(int)($_GET['after']??0));$st=$pdo->prepare("SELECT c.*,cu.name customer_name,ct.name contact_name FROM v10_call_logs c LEFT JOIN customers cu ON cu.id=c.customer_id LEFT JOIN contacts ct ON ct.id=c.contact_id WHERE c.company_id=? AND c.direction='inbound' AND c.id>? AND c.started_at>=DATE_SUB(NOW(),INTERVAL 10 MINUTE) AND (c.user_id IS NULL OR c.user_id=?) ORDER BY c.id");$st->execute([$cid,$after,$u['id']]);json_response(['ok'=>true,'items'=>$st->fetchAll()]);
  case 'calls':require_cap_v10('communications.read');$st=$pdo->prepare('SELECT c.*,cu.name customer_name,ct.name contact_name,u.name user_name FROM v10_call_logs c LEFT JOIN customers cu ON cu.id=c.customer_id LEFT JOIN contacts ct ON ct.id=c.contact_id LEFT JOIN users u ON u.id=c.user_id WHERE c.company_id=? ORDER BY c.started_at DESC LIMIT 300');$st->execute([$cid]);json_response(['ok'=>true,'items'=>$st->fetchAll()]);
  case 'call':require_cap_v10('communications.write');$b=body_json();$phone=trim((string)req($b,'phone',''));if(!preg_match('/^[0-9+*#]{2,20}$/',$phone))json_response(['ok'=>false,'error'=>'invalid_phone'],422);$customer=(int)req($b,'customer_id',0)?:null;$contact=(int)req($b,'contact_id',0)?:null;if($customer)tenant_ref('customers',$customer,$cid,true);if($contact){$st=$pdo->prepare('SELECT id FROM contacts WHERE id=? AND company_id=?');$st->execute([$contact,$cid]);if(!$st->fetchColumn())json_response(['ok'=>false,'error'=>'invalid_contact'],422);}$cfg=integration_settings($cid,'voip');$external='';$status='logged';if($cfg['enabled']&&!empty($cfg['settings']['ami_host'])){$s=$cfg['settings'];$fp=@fsockopen((string)$s['ami_host'],(int)($s['ami_port']??5038),$errno,$errstr,5);if($fp){$ext=trim((string)($u['extension']??''));$ctx=preg_replace('/[\r\n]/','',(string)($s['context']??'from-internal'));$amiUser=preg_replace('/[\r\n]/','',(string)($s['username']??''));$amiSecret=preg_replace('/[\r\n]/','',(string)($s['secret']??$s['password']??''));if($ext===''||!preg_match('/^[A-Za-z0-9_.-]{1,32}$/',$ext)){$status='extension_missing';fclose($fp);}else{stream_set_timeout($fp,5);fwrite($fp,"Action: Login\r\nUsername: $amiUser\r\nSecret: $amiSecret\r\nEvents: off\r\n\r\n");$login='';while(!str_contains($login,"\r\n\r\n")&&!feof($fp)){$login.=fgets($fp,1024)?:'';}if(!preg_match('/Response:\s*Success/i',$login)){$status='ami_login_failed';fclose($fp);}else{$payload="Action: Originate\r\nChannel: SIP/$ext\r\nContext: $ctx\r\nExten: $phone\r\nPriority: 1\r\nCallerID: CRM <$ext>\r\nAsync: true\r\n\r\nAction: Logoff\r\n\r\n";fwrite($fp,$payload);fclose($fp);$status='originated';}}}else$status='ami_failed';}$pdo->prepare('INSERT INTO v10_call_logs(company_id,user_id,customer_id,contact_id,direction,phone,external_id,status,notes) VALUES(?,?,?,?,?,?,?,?,?)')->execute([$cid,$u['id'],$customer,$contact,'outbound',$phone,$external,$status,req($b,'notes')]);$id=(int)$pdo->lastInsertId();if($customer)v10_timeline('customers',$customer,'call','Phone call',(string)req($b,'notes',''),'call',$id,(int)$u['id'],['phone'=>$phone,'status'=>$status]);json_response(['ok'=>true,'id'=>$id,'status'=>$status,'tel'=>'tel:'.$phone]);
  default:json_response(['ok'=>false,'error'=>'unknown_action'],404);
 }
}catch(Throwable $e){error_log($e->__toString());json_response(['ok'=>false,'error'=>'server_error','message'=>envv('APP_ENV','local')==='local'?$e->getMessage():'Internal server error'],500);}
