<?php
declare(strict_types=1);
require dirname(__DIR__).'/v10-lib.php';
$u=require_login();$cid=(int)$u['company_id'];require_cap_v10('crm.read');$pdo=db();
$uid=(int)$u['id'];$admin=can_v10('projects.write',$u)||can_v10('sales.write',$u);
$q=function(string $sql,array $args=[])use($pdo){$s=$pdo->prepare($sql);$s->execute($args);return$s->fetchAll();};
$one=function(string $sql,array $args=[])use($pdo){$s=$pdo->prepare($sql);$s->execute($args);return$s->fetchColumn();};
$todayTasks=$q("SELECT t.id,t.title,t.status,t.priority,t.due_date,p.name project_name FROM tasks t LEFT JOIN projects p ON p.id=t.project_id WHERE t.company_id=? AND NOT EXISTS(SELECT 1 FROM v10_record_deletions d WHERE d.company_id=t.company_id AND d.entity_type='tasks' AND d.entity_id=t.id) AND t.assignee_id=? AND t.status<>'done' AND DATE(t.due_date)=CURDATE() ORDER BY t.due_date",[$cid,$uid]);
$overFollow=$q("SELECT f.id,f.subject,f.due_at,c.name customer_name FROM followups f LEFT JOIN customers c ON c.id=f.customer_id WHERE f.company_id=? AND NOT EXISTS(SELECT 1 FROM v10_record_deletions d WHERE d.company_id=f.company_id AND d.entity_type='followups' AND d.entity_id=f.id) AND f.status='open' AND f.due_at<NOW()".($admin?'':' AND f.assigned_to=?')." ORDER BY f.due_at LIMIT 12",$admin?[$cid]:[$cid,$uid]);
$pipeline=$q("SELECT o.stage,o.currency,COUNT(*) items,COALESCE(SUM(o.amount),0) amount,COALESCE(NULLIF(ps.name_fa,''),o.stage) stage_name_fa,COALESCE(NULLIF(ps.name_en,''),o.stage) stage_name_en FROM opportunities o LEFT JOIN pipeline_stages ps ON ps.company_id=o.company_id AND ps.code=o.stage AND ps.pipeline_id=(SELECT p.id FROM pipelines p WHERE p.company_id=o.company_id AND p.entity_type='opportunity' ORDER BY p.is_default DESC,p.id LIMIT 1) WHERE o.company_id=? AND NOT EXISTS(SELECT 1 FROM v10_record_deletions d WHERE d.company_id=o.company_id AND d.entity_type='opportunities' AND d.entity_id=o.id) GROUP BY o.stage,o.currency,ps.name_fa,ps.name_en ORDER BY MIN(ps.position),o.stage,o.currency",[$cid]);
$stageFallback=['qualification'=>['ارزیابی','Qualification'],'proposal'=>['پیشنهاد','Proposal'],'negotiation'=>['مذاکره','Negotiation'],'won'=>['موفق','Won'],'lost'=>['از دست رفته','Lost']];foreach($pipeline as&$row){$fallback=$stageFallback[(string)$row['stage']]??[(string)$row['stage'],(string)$row['stage']];if((string)$row['stage_name_fa']===(string)$row['stage'])$row['stage_name_fa']=$fallback[0];if((string)$row['stage_name_en']===(string)$row['stage'])$row['stage_name_en']=$fallback[1];$row['stage_name']=($u['lang']??'fa')==='fa'?$row['stage_name_fa']:$row['stage_name_en'];}unset($row);
$targets=$q("SELECT u.id,u.name,t.target_amount,t.currency,COALESCE(SUM(CASE WHEN o.stage='won' AND DATE(o.updated_at) BETWEEN t.period_start AND t.period_end THEN o.amount ELSE 0 END),0) actual FROM v10_sales_targets t JOIN users u ON u.id=t.user_id LEFT JOIN opportunities o ON o.owner_id=u.id AND o.company_id=t.company_id AND o.currency=t.currency AND NOT EXISTS(SELECT 1 FROM v10_record_deletions d WHERE d.company_id=o.company_id AND d.entity_type='opportunities' AND d.entity_id=o.id) WHERE t.company_id=? AND CURDATE() BETWEEN t.period_start AND t.period_end GROUP BY u.id,u.name,t.target_amount,t.currency ORDER BY actual DESC",[$cid]);
$payments=$q("SELECT p.id,p.title,p.amount,p.currency,p.due_date,p.status,c.name customer_name FROM payment_milestones p LEFT JOIN customers c ON c.id=p.customer_id WHERE p.company_id=? AND NOT EXISTS(SELECT 1 FROM v10_record_deletions d WHERE d.company_id=p.company_id AND d.entity_type='payments' AND d.entity_id=p.id) AND p.status<>'paid' AND p.due_date<=DATE_ADD(CURDATE(),INTERVAL 14 DAY) ORDER BY p.due_date LIMIT 12",[$cid]);
$shipments=$q("SELECT s.id,s.shipment_no,s.status,s.eta,s.port_destination,c.name customer_name FROM shipments s LEFT JOIN customers c ON c.id=s.customer_id WHERE s.company_id=? AND NOT EXISTS(SELECT 1 FROM v10_record_deletions d WHERE d.company_id=s.company_id AND d.entity_type='shipments' AND d.entity_id=s.id) AND s.status NOT IN ('delivered','cancelled') ORDER BY s.eta IS NULL,s.eta LIMIT 12",[$cid]);
$legacy=[];$legacy['team']=$q("SELECT u.name,COALESCE(x.tasks,0) tasks,COALESCE(x.done_tasks,0) done_tasks FROM users u LEFT JOIN(SELECT t.assignee_id,COUNT(*) tasks,SUM(t.status='done') done_tasks FROM tasks t WHERE t.company_id=? AND NOT EXISTS(SELECT 1 FROM v10_record_deletions d WHERE d.company_id=t.company_id AND d.entity_type='tasks' AND d.entity_id=t.id) GROUP BY t.assignee_id)x ON x.assignee_id=u.id WHERE u.company_id=? AND u.active=1 ORDER BY done_tasks DESC LIMIT 12",[$cid,$cid]);$legacy['vertical']=$q("SELECT COALESCE(p.vertical,'General') vertical,COUNT(*) projects,ROUND(AVG(p.progress),1) avg_progress FROM projects p WHERE p.company_id=? AND NOT EXISTS(SELECT 1 FROM v10_record_deletions d WHERE d.company_id=p.company_id AND d.entity_type='projects' AND d.entity_id=p.id) GROUP BY p.vertical ORDER BY projects DESC",[$cid]);
json_response(['ok'=>true,'my_tasks_today'=>$todayTasks,'overdue_followups'=>$overFollow,'pipeline'=>$pipeline,'targets'=>$targets,'payments_due'=>$payments,'shipments'=>$shipments,'legacy'=>$legacy,'counts'=>['notifications'=>(int)$one('SELECT COUNT(*) FROM notifications WHERE company_id=? AND user_id=? AND read_at IS NULL',[$cid,$uid])]]);
