<?php
declare(strict_types=1);
require dirname(__DIR__).'/v10-lib.php';
$u=require_login();$cid=(int)$u['company_id'];$pdo=db();$method=$_SERVER['REQUEST_METHOD']??'GET';if($method!=='GET')verify_csrf();$action=(string)($_GET['action']??'jobs');
function import_allowed_entity(string $e): bool {return in_array($e,['customers','contacts','leads','opportunities','suppliers','projects','tasks'],true);}
function import_rows_from_file(string $path,string $ext): array {
 if(in_array($ext,['xlsx','xls'],true)){
   $autoload=dirname(__DIR__).'/vendor/autoload.php';if(!is_file($autoload))throw new RuntimeException('PhpSpreadsheet is not installed. Run composer install.');require_once $autoload;if(!class_exists('PhpOffice\\PhpSpreadsheet\\IOFactory'))throw new RuntimeException('PhpSpreadsheet is not available.');$book=\PhpOffice\PhpSpreadsheet\IOFactory::load($path);$sheet=$book->getActiveSheet();$rows=$sheet->toArray(null,true,true,false);return$rows;
 }
 $fh=fopen($path,'rb');if(!$fh)throw new RuntimeException('Cannot read file');$rows=[];while(($r=fgetcsv($fh,0,','))!==false)$rows[]=$r;fclose($fh);return$rows;
}
try{switch($action){
 case 'jobs':require_cap_v10('data.import');$st=$pdo->prepare('SELECT j.*,u.name user_name FROM import_jobs j JOIN users u ON u.id=j.user_id WHERE j.company_id=? ORDER BY j.created_at DESC LIMIT 100');$st->execute([$cid]);json_response(['ok'=>true,'items'=>$st->fetchAll()]);
 case 'export':require_cap_v10('data.export');$entity=(string)($_GET['entity']??'customers');$m=v10_meta($entity);require_cap_v10($m['read']);$fields=array_values(array_unique(array_merge(['id'],$m['fields'],['created_at','updated_at'])));$st=$pdo->prepare('SELECT '.implode(',',array_map('v10_identifier',$fields)).' FROM `'.$m['table'].'` t WHERE t.company_id=? AND '.v10_is_deleted_sql('t').' ORDER BY t.id DESC');$st->execute([$cid,$entity]);header('Content-Type:text/csv; charset=UTF-8');header('Content-Disposition: attachment; filename="'.$entity.'-'.date('Ymd-His').'.csv"');echo "\xEF\xBB\xBF";$out=fopen('php://output','w');fputcsv($out,$fields);while($r=$st->fetch(PDO::FETCH_ASSOC))fputcsv($out,$r);fclose($out);exit;
 case 'preview':require_cap_v10('data.import');$entity=(string)($_POST['entity']??'');if(!import_allowed_entity($entity))json_response(['ok'=>false,'error'=>'bad_entity'],422);if(empty($_FILES['file'])||!is_uploaded_file($_FILES['file']['tmp_name']))json_response(['ok'=>false,'error'=>'file_required'],422);$name=(string)$_FILES['file']['name'];$ext=strtolower(pathinfo($name,PATHINFO_EXTENSION));if(!in_array($ext,['csv','xlsx','xls'],true))json_response(['ok'=>false,'error'=>'bad_file_type'],422);$rows=import_rows_from_file($_FILES['file']['tmp_name'],$ext);if(!$rows)json_response(['ok'=>false,'error'=>'empty_file'],422);$headers=array_map(fn($x)=>trim((string)$x),array_shift($rows));$rows=array_slice($rows,0,5000);$token=v10_generate_token(24);$payload=['company_id'=>$cid,'user_id'=>(int)$u['id'],'entity'=>$entity,'filename'=>$name,'headers'=>$headers,'rows'=>$rows];$path=v10_storage_dir('imports').'/'.$token.'.json';if(file_put_contents($path,json_encode($payload,JSON_UNESCAPED_UNICODE),LOCK_EX)===false)json_response(['ok'=>false,'error'=>'storage_not_writable'],500);json_response(['ok'=>true,'token'=>$token,'headers'=>$headers,'sample'=>array_slice($rows,0,10),'allowed_fields'=>v10_meta($entity)['fields'],'total'=>count($rows)]);
 case 'commit':require_cap_v10('data.import');$b=body_json();$token=preg_replace('/[^A-Za-z0-9_\-]/','',(string)req($b,'token',''));$path=v10_storage_dir('imports').'/'.$token.'.json';if(!$token||!is_file($path))json_response(['ok'=>false,'error'=>'import_session_not_found'],404);$payload=json_decode((string)file_get_contents($path),true);if(!is_array($payload)||($payload['company_id']??0)!==$cid||($payload['user_id']??0)!==(int)$u['id'])json_response(['ok'=>false,'error'=>'forbidden'],403);$entity=(string)$payload['entity'];$m=v10_meta($entity);$mapping=(array)req($b,'mapping',[]);$strategy=clean_status((string)req($b,'duplicate_strategy','skip'),['skip','update','create'],'skip');$headers=$payload['headers'];$success=0;$failed=0;$errors=[];$pdo->beginTransaction();try{foreach($payload['rows'] as $idx=>$row){$data=[];foreach($mapping as $source=>$dest){if(!in_array($dest,$m['fields'],true))continue;$col=array_search($source,$headers,true);if($col!==false)$data[$dest]=$row[$col]??null;}if(!$data){$failed++;continue;}$dupId=0;if(isset($data['email'])&&$data['email']){$st=$pdo->prepare('SELECT id FROM `'.$m['table'].'` WHERE company_id=? AND email=? LIMIT 1');$st->execute([$cid,$data['email']]);$dupId=(int)($st->fetchColumn()?:0);}elseif(isset($data['name'])&&$data['name']){$st=$pdo->prepare('SELECT id FROM `'.$m['table'].'` WHERE company_id=? AND name=? LIMIT 1');$st->execute([$cid,$data['name']]);$dupId=(int)($st->fetchColumn()?:0);}elseif(isset($data['title'])&&$data['title']){$st=$pdo->prepare('SELECT id FROM `'.$m['table'].'` WHERE company_id=? AND title=? LIMIT 1');$st->execute([$cid,$data['title']]);$dupId=(int)($st->fetchColumn()?:0);}if($dupId&&!v10_record_exists($entity,$dupId,$cid))$dupId=0;if($dupId&&$strategy==='skip')continue;if($dupId&&$strategy==='update'){$sets=[];$args=[];foreach($data as $f=>$v){$sets[]=v10_identifier($f).'=?';$args[]=$v;}$args[]=$dupId;$args[]=$cid;$pdo->prepare('UPDATE `'.$m['table'].'` SET '.implode(',',$sets).' WHERE id=? AND company_id=?')->execute($args);$success++;continue;}$names=['company_id'];$vals=['?'];$args=[$cid];foreach($data as $f=>$v){$names[]=v10_identifier($f);$vals[]='?';$args[]=$v;}try{$pdo->prepare('INSERT INTO `'.$m['table'].'`('.implode(',',$names).') VALUES('.implode(',',$vals).')')->execute($args);$success++;}catch(Throwable $e){$failed++;if(count($errors)<50)$errors[]=['row'=>$idx+2,'message'=>$e->getMessage()];}}$pdo->commit();$pdo->prepare('INSERT INTO import_jobs(company_id,user_id,entity_type,filename,total_rows,success_rows,failed_rows,errors_json) VALUES(?,?,?,?,?,?,?,?)')->execute([$cid,$u['id'],$entity,$payload['filename'],count($payload['rows']),$success,$failed,json_encode($errors,JSON_UNESCAPED_UNICODE)]);@unlink($path);json_response(['ok'=>true,'success'=>$success,'failed'=>$failed,'errors'=>$errors]);}catch(Throwable $e){$pdo->rollBack();throw$e;}
 default:json_response(['ok'=>false,'error'=>'unknown_action'],404);
}}catch(Throwable $e){error_log($e->__toString());json_response(['ok'=>false,'error'=>'server_error','message'=>envv('APP_ENV','local')==='local'?$e->getMessage():'Internal server error'],500);}
