<?php
declare(strict_types=1);
require dirname(__DIR__).'/automation-engine.php';
$u=require_login();$cid=(int)$u['company_id'];$pdo=db();$method=$_SERVER['REQUEST_METHOD']??'GET';if($method!=='GET')verify_csrf();$action=(string)($_GET['action']??'list');
try{switch($action){
 case 'list':require_cap_v10('admin.settings.read');$st=$pdo->prepare('SELECT id,provider_type,provider_name,settings_json,enabled,updated_at FROM integration_settings WHERE company_id=? ORDER BY provider_type,provider_name');$st->execute([$cid]);$rows=$st->fetchAll();foreach($rows as &$r){$s=integration_decode((string)$r['settings_json']);foreach(['password','token','secret','api_key','imap_password'] as $k)if(isset($s[$k])&&$s[$k]!=='')$s[$k]='••••••••';$r['settings']=$s;unset($r['settings_json']);}json_response(['ok'=>true,'items'=>$rows]);
 case 'save':require_cap_v10('admin.settings.write');$b=body_json();$id=(int)req($b,'id',0);$type=clean_status((string)req($b,'provider_type','email'),['email','sms','voip'],'email');$name=trim((string)req($b,'provider_name',''));if(!$name)json_response(['ok'=>false,'error'=>'provider_required'],422);$settings=(array)req($b,'settings',[]);$enabled=!empty($b['enabled'])?1:0;$old=[];if($id){$st=$pdo->prepare('SELECT settings_json FROM integration_settings WHERE id=? AND company_id=?');$st->execute([$id,$cid]);$raw=$st->fetchColumn();if($raw===false)json_response(['ok'=>false,'error'=>'not_found'],404);$old=integration_decode((string)$raw);}foreach(['password','token','secret','api_key','imap_password'] as $k)if(($settings[$k]??'')==='••••••••'||($settings[$k]??'')==='')if(isset($old[$k]))$settings[$k]=$old[$k];if($id)$pdo->prepare('UPDATE integration_settings SET provider_type=?,provider_name=?,settings_json=?,enabled=?,updated_by=? WHERE id=? AND company_id=?')->execute([$type,$name,integration_encode($settings),$enabled,$u['id'],$id,$cid]);else{$pdo->prepare('INSERT INTO integration_settings(company_id,provider_type,provider_name,settings_json,enabled,updated_by) VALUES(?,?,?,?,?,?)')->execute([$cid,$type,$name,integration_encode($settings),$enabled,$u['id']]);$id=(int)$pdo->lastInsertId();}audit('save','integration',$id,['type'=>$type,'provider'=>$name]);json_response(['ok'=>true,'id'=>$id]);
 case 'delete':require_cap_v10('admin.settings.write');$b=body_json();$id=(int)req($b,'id',0);$pdo->prepare('DELETE FROM integration_settings WHERE id=? AND company_id=?')->execute([$id,$cid]);audit('delete','integration',$id);json_response(['ok'=>true]);
 case 'test':require_cap_v10('admin.settings.write');$b=body_json();$id=(int)req($b,'id',0);$st=$pdo->prepare('SELECT provider_type,provider_name,settings_json,enabled FROM integration_settings WHERE id=? AND company_id=?');$st->execute([$id,$cid]);$r=$st->fetch();if(!$r)json_response(['ok'=>false,'error'=>'not_found'],404);$settings=integration_decode((string)$r['settings_json']);if($r['provider_type']==='email'){[$ok,$msg]=smtp_send($settings,(string)$u['email'],'CRM integration test','<p>SMTP integration is working.</p>');json_response(['ok'=>$ok,'message'=>$msg],$ok?200:502);}if($r['provider_type']==='sms'){if(empty($u['phone']))json_response(['ok'=>false,'error'=>'user_phone_missing'],422);[$ok,$msg]=sms_send_v10((string)$r['provider_name'],$settings,(string)$u['phone'],'CRM SMS integration test');json_response(['ok'=>$ok,'message'=>$msg],$ok?200:502);}if($r['provider_type']==='voip'){if(empty($settings['ami_host']))json_response(['ok'=>false,'error'=>'ami_host_missing'],422);$fp=@fsockopen((string)$settings['ami_host'],(int)($settings['ami_port']??5038),$errno,$errstr,5);if($fp){fclose($fp);json_response(['ok'=>true,'message'=>'AMI socket connected']);}json_response(['ok'=>false,'message'=>$errstr],502);}json_response(['ok'=>false,'error'=>'unsupported'],422);
 default:json_response(['ok'=>false,'error'=>'unknown_action'],404);
}}catch(Throwable $e){error_log($e->__toString());json_response(['ok'=>false,'error'=>'server_error','message'=>envv('APP_ENV','local')==='local'?$e->getMessage():'Internal server error'],500);}
