<?php
declare(strict_types=1);
require dirname(__DIR__).'/automation-engine.php';
$u=require_login();$cid=(int)$u['company_id'];$pdo=db();$method=$_SERVER['REQUEST_METHOD']??'GET';if($method!=='GET')verify_csrf();$action=(string)($_GET['action']??'board');
function pipeline_entity(string $value): string {return clean_status($value,['leads','opportunities'],'opportunities');}
function pipeline_kind(string $entity): string {return $entity==='leads'?'lead':'opportunity';}
function pipeline_default_stages(string $entity): array {return $entity==='leads'?[['new','جدید','New',10,0,0],['qualified','واجد شرایط','Qualified',30,0,0],['proposal','پیشنهاد','Proposal',60,0,0],['won','موفق','Won',100,1,1],['lost','از دست رفته','Lost',0,1,0]]:[['qualification','ارزیابی','Qualification',20,0,0],['proposal','پیشنهاد','Proposal',50,0,0],['negotiation','مذاکره','Negotiation',75,0,0],['won','موفق','Won',100,1,1],['lost','از دست رفته','Lost',0,1,0]];}
function pipeline_id(PDO $pdo,int $cid,string $entity,bool $create=false): int {$kind=pipeline_kind($entity);$st=$pdo->prepare('SELECT id FROM pipelines WHERE company_id=? AND entity_type=? ORDER BY is_default DESC,id LIMIT 1');$st->execute([$cid,$kind]);$id=(int)($st->fetchColumn()?:0);if(!$id&&$create){$pdo->prepare('INSERT INTO pipelines(company_id,name,entity_type,is_default) VALUES(?,?,?,1)')->execute([$cid,ucfirst($kind).' pipeline',$kind]);$id=(int)$pdo->lastInsertId();$ins=$pdo->prepare('INSERT INTO pipeline_stages(company_id,pipeline_id,code,name_fa,name_en,position,probability,is_closed,is_won) VALUES(?,?,?,?,?,?,?,?,?)');foreach(pipeline_default_stages($entity) as $pos=>$s)$ins->execute([$cid,$id,$s[0],$s[1],$s[2],$pos,$s[3],$s[4],$s[5]]);}return$id;}
try{switch($action){
 case 'stages':require_cap_v10('sales.read');$entity=pipeline_entity((string)($_GET['entity']??'opportunities'));$pid=pipeline_id($pdo,$cid,$entity,true);$st=$pdo->prepare('SELECT * FROM pipeline_stages WHERE company_id=? AND pipeline_id=? ORDER BY position,id');$st->execute([$cid,$pid]);json_response(['ok'=>true,'pipeline_id'=>$pid,'items'=>$st->fetchAll()]);
 case 'board':require_cap_v10('sales.read');$entity=pipeline_entity((string)($_GET['entity']??'opportunities'));$m=v10_meta($entity);$pid=pipeline_id($pdo,$cid,$entity,true);$st=$pdo->prepare('SELECT * FROM pipeline_stages WHERE company_id=? AND pipeline_id=? ORDER BY position,id');$st->execute([$cid,$pid]);$stages=$st->fetchAll();$amount=$entity==='leads'?'value':'amount';$st=$pdo->prepare('SELECT t.*,u.name owner_name FROM `'.$m['table'].'` t LEFT JOIN users u ON u.id=t.owner_id WHERE t.company_id=? AND '.v10_is_deleted_sql('t').' ORDER BY t.updated_at DESC');$st->execute([$cid,$entity]);$items=$st->fetchAll();json_response(['ok'=>true,'stages'=>$stages,'items'=>$items,'amount_field'=>$amount]);
 case 'move':require_cap_v10('sales.write');$b=body_json();$entity=pipeline_entity((string)req($b,'entity','opportunities'));$id=(int)req($b,'id',0);$stage=(string)req($b,'stage','');$pid=pipeline_id($pdo,$cid,$entity,true);$st=$pdo->prepare('SELECT probability FROM pipeline_stages WHERE company_id=? AND pipeline_id=? AND code=?');$st->execute([$cid,$pid,$stage]);$prob=$st->fetchColumn();if($prob===false)json_response(['ok'=>false,'error'=>'invalid_stage'],422);$before=v10_require_record($entity,$id,$cid);$sql='UPDATE `'.v10_meta($entity)['table'].'` SET stage=?'.($entity==='opportunities'?',probability=?':'').' WHERE id=? AND company_id=?';$args=$entity==='opportunities'?[$stage,(int)$prob,$id,$cid]:[$stage,$id,$cid];$pdo->prepare($sql)->execute($args);$fresh=v10_require_record($entity,$id,$cid);v10_timeline($entity,$id,'stage','Stage changed',(string)$before['stage'].' → '.$stage,null,null,(int)$u['id']);v10_run_event_rules($cid,$entity,'stage_changed',$fresh,$id,'stage');json_response(['ok'=>true]);
 case 'save_stage':require_cap_v10('admin.settings.write');$b=body_json();$entity=pipeline_entity((string)req($b,'entity','opportunities'));$pid=pipeline_id($pdo,$cid,$entity,true);$id=(int)req($b,'id',0);$code=preg_replace('/[^a-z0-9_-]/','',strtolower((string)req($b,'code','')));if(!$code)json_response(['ok'=>false,'error'=>'code_required'],422);$vals=[$code,trim((string)req($b,'name_fa',$code)),trim((string)req($b,'name_en',$code)),(int)req($b,'position',0),max(0,min(100,(int)req($b,'probability',0))),!empty($b['is_closed'])?1:0,!empty($b['is_won'])?1:0];if($id)$pdo->prepare('UPDATE pipeline_stages SET code=?,name_fa=?,name_en=?,position=?,probability=?,is_closed=?,is_won=? WHERE id=? AND company_id=? AND pipeline_id=?')->execute([...$vals,$id,$cid,$pid]);else{$pdo->prepare('INSERT INTO pipeline_stages(company_id,pipeline_id,code,name_fa,name_en,position,probability,is_closed,is_won) VALUES(?,?,?,?,?,?,?,?,?)')->execute([$cid,$pid,...$vals]);$id=(int)$pdo->lastInsertId();}json_response(['ok'=>true,'id'=>$id]);
 case 'delete_stage':require_cap_v10('admin.settings.write');$b=body_json();$entity=pipeline_entity((string)req($b,'entity','opportunities'));$pid=pipeline_id($pdo,$cid,$entity,true);$id=(int)req($b,'id',0);$st=$pdo->prepare('SELECT code FROM pipeline_stages WHERE id=? AND company_id=? AND pipeline_id=?');$st->execute([$id,$cid,$pid]);$code=(string)$st->fetchColumn();if(!$code)json_response(['ok'=>false,'error'=>'not_found'],404);$m=v10_meta($entity);$q=$pdo->prepare('SELECT COUNT(*) FROM `'.$m['table'].'` WHERE company_id=? AND stage=?');$q->execute([$cid,$code]);if((int)$q->fetchColumn()>0)json_response(['ok'=>false,'error'=>'stage_in_use'],422);$pdo->prepare('DELETE FROM pipeline_stages WHERE id=? AND company_id=?')->execute([$id,$cid]);json_response(['ok'=>true]);
 case 'convert_lead':require_cap_v10('sales.write');$b=body_json();$id=(int)req($b,'lead_id',0);$lead=v10_require_record('leads',$id,$cid);$baseCurrency=strtoupper((string)v10_company_setting($cid,'currency','IRR'));$pdo->beginTransaction();try{$name=trim((string)($lead['customer_name']?:$lead['title']));$pdo->prepare("INSERT INTO customers(company_id,name,type,phone,email,status,owner_id,notes) VALUES(?,?,'company',?,?,'active',?,?)")->execute([$cid,$name,$lead['phone'],$lead['email'],$lead['owner_id'],'Converted from lead #'.$id]);$customer=(int)$pdo->lastInsertId();$contact=null;if($lead['phone']||$lead['email']){$pdo->prepare('INSERT INTO contacts(company_id,customer_id,name,phone,email,notes) VALUES(?,?,?,?,?,?)')->execute([$cid,$customer,$name,$lead['phone'],$lead['email'],'Converted from lead #'.$id]);$contact=(int)$pdo->lastInsertId();}$pdo->prepare("INSERT INTO opportunities(company_id,customer_id,title,stage,probability,amount,currency,owner_id,notes) VALUES(?,?,?,'qualification',20,?,?,?,?)")->execute([$cid,$customer,$lead['title'],(float)$lead['value'],$baseCurrency,$lead['owner_id'],'Converted from lead #'.$id]);$opportunity=(int)$pdo->lastInsertId();$pdo->prepare("UPDATE leads SET stage='won' WHERE id=? AND company_id=?")->execute([$id,$cid]);$pdo->commit();v10_timeline('leads',$id,'conversion','Lead converted','Customer #'.$customer.' · Opportunity #'.$opportunity,'opportunities',$opportunity,(int)$u['id']);json_response(['ok'=>true,'customer_id'=>$customer,'contact_id'=>$contact,'opportunity_id'=>$opportunity]);}catch(Throwable $e){$pdo->rollBack();throw$e;}
 default:json_response(['ok'=>false,'error'=>'unknown_action'],404);
}}catch(Throwable $e){error_log($e->__toString());json_response(['ok'=>false,'error'=>'server_error','message'=>envv('APP_ENV','local')==='local'?$e->getMessage():'Internal server error'],500);}
