<?php
declare(strict_types=1);
require dirname(__DIR__).'/bootstrap.php';
$pdo=db();$action=(string)($_GET['action']??'tickets');if(($_SERVER['REQUEST_METHOD']??'GET')!=='GET')verify_csrf();$pu=$_SESSION['portal_user']??null;if(!$pu)json_response(['ok'=>false,'error'=>'unauthorized'],401);$cid=(int)$pu['company_id'];$customer=(int)$pu['customer_id'];
try{switch($action){
case'tickets':$st=$pdo->prepare('SELECT id,ticket_no,subject,priority,status,sla_due_at,created_at,updated_at FROM v10_tickets WHERE company_id=? AND customer_id=? ORDER BY updated_at DESC');$st->execute([$cid,$customer]);json_response(['ok'=>true,'items'=>$st->fetchAll()]);
case'ticket':$id=(int)($_GET['id']??0);$st=$pdo->prepare('SELECT id,ticket_no,subject,description,priority,status,sla_due_at,created_at FROM v10_tickets WHERE id=? AND company_id=? AND customer_id=?');$st->execute([$id,$cid,$customer]);$ticket=$st->fetch();if(!$ticket)json_response(['ok'=>false,'error'=>'not_found'],404);$st=$pdo->prepare('SELECT r.body,r.created_at,u.name user_name,r.portal_user_id FROM v10_ticket_replies r LEFT JOIN users u ON u.id=r.user_id WHERE r.company_id=? AND r.ticket_id=? ORDER BY r.created_at');$st->execute([$cid,$id]);json_response(['ok'=>true,'ticket'=>$ticket,'replies'=>$st->fetchAll()]);
case'create':$b=body_json();$subject=trim((string)req($b,'subject',''));if(!$subject)json_response(['ok'=>false,'error'=>'subject_required'],422);$priority=clean_status((string)req($b,'priority','medium'),['low','medium','high','urgent'],'medium');$pol=json_decode((string)v10_company_setting($cid,'sla_policies','{}'),true)?:[];$hours=max(1,(int)($pol[$priority]??24));$no='TKT-'.date('Ymd-His').'-'.random_int(10,99);$pdo->prepare("INSERT INTO v10_tickets(company_id,customer_id,ticket_no,subject,description,priority,status,sla_due_at) VALUES(?,?,?,?,?,?,'open',DATE_ADD(NOW(),INTERVAL ? HOUR))")->execute([$cid,$customer,$no,$subject,req($b,'description'),$priority,$hours]);json_response(['ok'=>true,'id'=>(int)$pdo->lastInsertId()]);
case'reply':$b=body_json();$id=(int)req($b,'ticket_id',0);$st=$pdo->prepare('SELECT 1 FROM v10_tickets WHERE id=? AND company_id=? AND customer_id=?');$st->execute([$id,$cid,$customer]);if(!$st->fetchColumn())json_response(['ok'=>false,'error'=>'not_found'],404);$body=trim((string)req($b,'body',''));if(!$body)json_response(['ok'=>false,'error'=>'body_required'],422);$pdo->prepare('INSERT INTO v10_ticket_replies(company_id,ticket_id,portal_user_id,body) VALUES(?,?,?,?)')->execute([$cid,$id,$pu['id'],$body]);$pdo->prepare("UPDATE v10_tickets SET status='open' WHERE id=? AND company_id=?")->execute([$id,$cid]);json_response(['ok'=>true]);
default:json_response(['ok'=>false,'error'=>'unknown_action'],404);}}catch(Throwable $e){error_log($e->__toString());json_response(['ok'=>false,'error'=>'server_error'],500);}
