<?php
declare(strict_types=1);
require dirname(__DIR__).'/v10-lib.php';
$u=require_login();$cid=(int)$u['company_id'];$pdo=db();$method=$_SERVER['REQUEST_METHOD']??'GET';if($method!=='GET')verify_csrf();$action=(string)($_GET['action']??'classic');
function report_defs_v10(): array {return [
 'customers'=>['table'=>'customers','fields'=>['id','name','type','phone','email','city','status','owner_id','created_at']],
 'contacts'=>['table'=>'contacts','fields'=>['id','name','job_title','phone','email','customer_id','created_at']],
 'leads'=>['table'=>'leads','fields'=>['id','title','customer_name','source','vertical','stage','value','currency','owner_id','created_at']],
 'opportunities'=>['table'=>'opportunities','fields'=>['id','title','stage','amount','currency','probability','customer_id','owner_id','expected_close_date','created_at']],
 'projects'=>['table'=>'projects','fields'=>['id','name','code','vertical','category','status','progress','budget','currency','manager_id','start_date','due_date','created_at']],
 'tasks'=>['table'=>'tasks','fields'=>['id','title','status','priority','project_id','assignee_id','due_date','estimated_hours','created_at']],
 'suppliers'=>['table'=>'suppliers','fields'=>['id','name','category','contact_name','phone','email','status','created_at']],
 'rfqs'=>['table'=>'rfqs','fields'=>['id','rfq_no','title','vertical','status','currency','due_date','created_at']],
 'quotations'=>['table'=>'quotations','fields'=>['id','quote_no','title','amount','subtotal','discount_amount','tax_amount','currency','status','valid_until','created_at']],
 'payments'=>['table'=>'payment_milestones','fields'=>['id','title','method','currency','amount','due_date','status','paid_at','created_at']],
 'shipments'=>['table'=>'shipments','fields'=>['id','shipment_no','status','mode','incoterm','container_no','bl_no','forwarder','port_destination','etd','eta','created_at']],
 ];}
try{switch($action){
 case 'classic':require_cap_v10('reports.read');$q=function($sql,$args)use($pdo){$s=$pdo->prepare($sql);$s->execute($args);return$s->fetchAll();};$vertical=$q("SELECT COALESCE(p.vertical,'General') vertical,COUNT(*) projects,ROUND(AVG(p.progress),1) avg_progress,SUM(p.budget) budget FROM projects p WHERE p.company_id=? AND ".v10_is_deleted_sql('p')." GROUP BY p.vertical ORDER BY projects DESC",[$cid,'projects']);$team=$q("SELECT u.name,COALESCE(t.tasks,0) tasks,COALESCE(t.done_tasks,0) done_tasks,COALESCE(te.minutes,0) minutes FROM users u LEFT JOIN (SELECT x.assignee_id,COUNT(*) tasks,SUM(x.status='done') done_tasks FROM tasks x WHERE x.company_id=? AND ".v10_is_deleted_sql('x')." GROUP BY x.assignee_id)t ON t.assignee_id=u.id LEFT JOIN (SELECT user_id,SUM(minutes) minutes FROM time_entries WHERE company_id=? GROUP BY user_id)te ON te.user_id=u.id WHERE u.company_id=? ORDER BY done_tasks DESC,u.name",[$cid,'tasks',$cid,$cid]);$pipeline=$q('SELECT o.stage,COUNT(*) items,SUM(o.amount) amount FROM opportunities o WHERE o.company_id=? AND '.v10_is_deleted_sql('o').' GROUP BY o.stage',[$cid,'opportunities']);$quotes=$q('SELECT q.status,COUNT(*) items,SUM(q.amount) amount FROM quotations q WHERE q.company_id=? AND '.v10_is_deleted_sql('q').' GROUP BY q.status',[$cid,'quotations']);json_response(['ok'=>true,'by_vertical'=>$vertical,'team'=>$team,'pipeline'=>$pipeline,'quotes'=>$quotes]);
 case 'fields':require_cap_v10('reports.read');$module=(string)($_GET['module']??'customers');$defs=report_defs_v10();if(!isset($defs[$module]))json_response(['ok'=>false,'error'=>'bad_module'],422);json_response(['ok'=>true,'fields'=>$defs[$module]['fields']]);
 case 'run':require_cap_v10('reports.read');$b=body_json();$module=(string)req($b,'module','customers');$defs=report_defs_v10();if(!isset($defs[$module]))json_response(['ok'=>false,'error'=>'bad_module'],422);$def=$defs[$module];$allowed=$def['fields'];$fields=array_values(array_intersect((array)req($b,'fields',$allowed),$allowed));if(!$fields)$fields=array_slice($allowed,0,6);$where=['t.company_id=?',v10_is_deleted_sql('t')];$args=[$cid,$module];$filters=(array)req($b,'filters',[]);if(isset($filters['status'])&&!in_array('status',$allowed,true)&&in_array('stage',$allowed,true)){$filters['stage']=$filters['status'];unset($filters['status']);}foreach($filters as $f=>$v){if($v===''||!in_array($f,$allowed,true))continue;$where[]='t.'.v10_identifier($f).'=?';$args[]=$v;}$from=(string)req($b,'date_from','');$to=(string)req($b,'date_to','');if(in_array('created_at',$allowed,true)&&$from){$where[]='t.created_at>=?';$args[]=$from.' 00:00:00';}if(in_array('created_at',$allowed,true)&&$to){$where[]='t.created_at<=?';$args[]=$to.' 23:59:59';}$group=(string)req($b,'group_by','');$summary=(string)req($b,'summary','count');$summaryField=(string)req($b,'summary_field','');if($group&&in_array($group,$allowed,true)){$sel=[v10_identifier($group).' group_value','COUNT(*) row_count'];if(in_array($summary,['sum','avg'],true)&&$summaryField&&in_array($summaryField,$allowed,true))$sel[]=strtoupper($summary).'('.v10_identifier($summaryField).') summary_value';$sql='SELECT '.implode(',',$sel).' FROM `'.$def['table'].'` t WHERE '.implode(' AND ',$where).' GROUP BY '.v10_identifier($group).' ORDER BY row_count DESC LIMIT 1000';$st=$pdo->prepare($sql);$st->execute($args);$rows=$st->fetchAll();json_response(['ok'=>true,'fields'=>$rows?array_keys($rows[0]):['group_value','row_count'],'rows'=>$rows,'grouped'=>true]);}$sql='SELECT '.implode(',',array_map('v10_identifier',$fields)).' FROM `'.$def['table'].'` t WHERE '.implode(' AND ',$where).' ORDER BY id DESC LIMIT 2000';$st=$pdo->prepare($sql);$st->execute($args);$rows=$st->fetchAll();json_response(['ok'=>true,'fields'=>$fields,'rows'=>$rows,'count'=>count($rows),'grouped'=>false]);
 case 'saved':require_cap_v10('reports.read');$st=$pdo->prepare('SELECT * FROM saved_reports WHERE company_id=? AND (user_id=? OR is_shared=1) ORDER BY name');$st->execute([$cid,$u['id']]);$items=$st->fetchAll();foreach($items as &$r)$r['config']=v10_json_decode((string)$r['config_json']);json_response(['ok'=>true,'items'=>$items]);
 case 'save':require_cap_v10('reports.write');$b=body_json();$id=(int)req($b,'id',0);$name=trim((string)req($b,'name',''));$module=(string)req($b,'module','customers');if(!$name||!isset(report_defs_v10()[$module]))json_response(['ok'=>false,'error'=>'bad_report'],422);$config=json_encode((array)req($b,'config',[]),JSON_UNESCAPED_UNICODE);if($id)$pdo->prepare('UPDATE saved_reports SET name=?,module=?,config_json=?,is_shared=? WHERE id=? AND company_id=? AND (user_id=? OR ?=1)')->execute([$name,$module,$config,!empty($b['is_shared'])?1:0,$id,$cid,$u['id'],can_v10('admin.settings.write',$u)?1:0]);else{$pdo->prepare('INSERT INTO saved_reports(company_id,user_id,name,module,config_json,is_shared) VALUES(?,?,?,?,?,?)')->execute([$cid,$u['id'],$name,$module,$config,!empty($b['is_shared'])?1:0]);$id=(int)$pdo->lastInsertId();}json_response(['ok'=>true,'id'=>$id]);
 case 'delete':require_cap_v10('reports.write');$b=body_json();$id=(int)req($b,'id',0);if(can_v10('admin.settings.write',$u))$pdo->prepare('DELETE FROM saved_reports WHERE id=? AND company_id=?')->execute([$id,$cid]);else$pdo->prepare('DELETE FROM saved_reports WHERE id=? AND company_id=? AND user_id=?')->execute([$id,$cid,$u['id']]);json_response(['ok'=>true]);
 default:json_response(['ok'=>false,'error'=>'unknown_action'],404);
}}catch(Throwable $e){error_log($e->__toString());json_response(['ok'=>false,'error'=>'server_error','message'=>envv('APP_ENV','local')==='local'?$e->getMessage():'Internal server error'],500);}
