<?php
declare(strict_types=1);
require dirname(__DIR__).'/v10-lib.php';
$u=require_login();$cid=(int)$u['company_id'];$pdo=db();$method=$_SERVER['REQUEST_METHOD']??'GET';if($method!=='GET')verify_csrf();$action=(string)($_GET['action']??'tickets');
try{switch($action){
 case 'tickets':require_cap_v10('service.read');$args=[$cid];$scope='';if(!can_v10('service.write',$u)&&!can_v10('admin.users.read',$u)){$scope=' AND (t.owner_id=? OR t.owner_id IS NULL)';$args[]=$u['id'];}$st=$pdo->prepare('SELECT t.*,c.name customer_name,ct.name contact_name,us.name owner_name FROM v10_tickets t LEFT JOIN customers c ON c.id=t.customer_id LEFT JOIN contacts ct ON ct.id=t.contact_id LEFT JOIN users us ON us.id=t.owner_id WHERE t.company_id=?'.$scope.' ORDER BY FIELD(t.status,\'open\',\'pending\',\'resolved\',\'closed\'),t.sla_due_at IS NULL,t.sla_due_at');$st->execute($args);json_response(['ok'=>true,'items'=>$st->fetchAll()]);
 case 'ticket':require_cap_v10('service.read');$id=(int)($_GET['id']??0);$st=$pdo->prepare('SELECT t.*,c.name customer_name,ct.name contact_name,us.name owner_name FROM v10_tickets t LEFT JOIN customers c ON c.id=t.customer_id LEFT JOIN contacts ct ON ct.id=t.contact_id LEFT JOIN users us ON us.id=t.owner_id WHERE t.id=? AND t.company_id=?');$st->execute([$id,$cid]);$ticket=$st->fetch();if(!$ticket)json_response(['ok'=>false,'error'=>'not_found'],404);$st=$pdo->prepare('SELECT r.*,u.name user_name FROM v10_ticket_replies r LEFT JOIN users u ON u.id=r.user_id WHERE r.company_id=? AND r.ticket_id=? ORDER BY r.created_at');$st->execute([$cid,$id]);json_response(['ok'=>true,'ticket'=>$ticket,'replies'=>$st->fetchAll()]);
 case 'save_ticket':require_cap_v10('service.write');$b=body_json();$id=(int)req($b,'id',0);if(!$id&&empty($b['sla_due_at'])){$pol=json_decode((string)v10_company_setting($cid,'sla_policies','{}'),true)?:[];$hours=max(1,(int)($pol[(string)req($b,'priority','medium')]??24));$b['sla_due_at']=date('Y-m-d H:i:s',time()+$hours*3600);}$customer=(int)req($b,'customer_id',0)?:null;$contact=(int)req($b,'contact_id',0)?:null;$owner=(int)req($b,'owner_id',0)?:null;if($customer)tenant_ref('customers',$customer,$cid,true);if($owner)tenant_ref('users',$owner,$cid,true);if($contact){$st=$pdo->prepare('SELECT id FROM contacts WHERE id=? AND company_id=?');$st->execute([$contact,$cid]);if(!$st->fetchColumn())json_response(['ok'=>false,'error'=>'invalid_contact'],422);}$subject=trim((string)req($b,'subject',''));if(!$subject)json_response(['ok'=>false,'error'=>'subject_required'],422);$ticketNo=(string)req($b,'ticket_no','');if(!$ticketNo)$ticketNo='TKT-'.date('Ymd-His');$vals=[$customer,$contact,$owner,$ticketNo,$subject,req($b,'description'),req($b,'priority','medium'),req($b,'status','open'),req($b,'sla_due_at')?:null];if($id)$pdo->prepare('UPDATE v10_tickets SET customer_id=?,contact_id=?,owner_id=?,ticket_no=?,subject=?,description=?,priority=?,status=?,sla_due_at=? WHERE id=? AND company_id=?')->execute([...$vals,$id,$cid]);else{$pdo->prepare('INSERT INTO v10_tickets(company_id,customer_id,contact_id,owner_id,ticket_no,subject,description,priority,status,sla_due_at) VALUES(?,?,?,?,?,?,?,?,?,?)')->execute([$cid,...$vals]);$id=(int)$pdo->lastInsertId();}audit('save','ticket',$id);json_response(['ok'=>true,'id'=>$id]);
 case 'delete_ticket':require_cap_v10('service.write');$b=body_json();$id=(int)req($b,'id',0);$pdo->beginTransaction();$pdo->prepare('DELETE FROM v10_ticket_replies WHERE company_id=? AND ticket_id=?')->execute([$cid,$id]);$pdo->prepare('DELETE FROM v10_tickets WHERE company_id=? AND id=?')->execute([$cid,$id]);$pdo->commit();audit('delete','ticket',$id);json_response(['ok'=>true]);
 case 'reply':require_cap_v10('service.write');$b=body_json();$ticket=(int)req($b,'ticket_id',0);$st=$pdo->prepare('SELECT customer_id FROM v10_tickets WHERE id=? AND company_id=?');$st->execute([$ticket,$cid]);$found=$st->fetchColumn();if($found===false)json_response(['ok'=>false,'error'=>'not_found'],404);$cust=(int)($found?:0);$body=trim((string)req($b,'body',''));if(!$body)json_response(['ok'=>false,'error'=>'body_required'],422);$pdo->prepare('INSERT INTO v10_ticket_replies(company_id,ticket_id,user_id,body,is_canned) VALUES(?,?,?,?,?)')->execute([$cid,$ticket,$u['id'],$body,!empty($b['is_canned'])?1:0]);if($cust)v10_timeline('customers',$cust,'ticket','Ticket reply',$body,'ticket',$ticket,(int)$u['id']);json_response(['ok'=>true,'id'=>(int)$pdo->lastInsertId()]);
 case 'delete_reply':require_cap_v10('service.write');$b=body_json();$pdo->prepare('DELETE FROM v10_ticket_replies WHERE id=? AND company_id=?')->execute([(int)req($b,'id',0),$cid]);json_response(['ok'=>true]);
 case 'canned':require_cap_v10('service.read');$st=$pdo->prepare('SELECT * FROM v10_canned_replies WHERE company_id=? ORDER BY title');$st->execute([$cid]);json_response(['ok'=>true,'items'=>$st->fetchAll()]);
 case 'save_canned':require_cap_v10('service.write');$b=body_json();$id=(int)req($b,'id',0);$title=trim((string)req($b,'title',''));$body=trim((string)req($b,'body',''));if(!$title||!$body)json_response(['ok'=>false,'error'=>'required'],422);if($id)$pdo->prepare('UPDATE v10_canned_replies SET title=?,body=? WHERE id=? AND company_id=?')->execute([$title,$body,$id,$cid]);else{$pdo->prepare('INSERT INTO v10_canned_replies(company_id,title,body) VALUES(?,?,?)')->execute([$cid,$title,$body]);$id=(int)$pdo->lastInsertId();}json_response(['ok'=>true,'id'=>$id]);
 case 'delete_canned':require_cap_v10('service.write');$b=body_json();$pdo->prepare('DELETE FROM v10_canned_replies WHERE id=? AND company_id=?')->execute([(int)req($b,'id',0),$cid]);json_response(['ok'=>true]);
 case 'portal_users':require_cap_v10('service.write');$st=$pdo->prepare('SELECT p.id,p.customer_id,p.contact_id,p.email,p.active,p.created_at,c.name customer_name FROM v10_portal_users p JOIN customers c ON c.id=p.customer_id WHERE p.company_id=? ORDER BY p.active DESC,p.email');$st->execute([$cid]);json_response(['ok'=>true,'items'=>$st->fetchAll()]);
 case 'save_portal_user':require_cap_v10('service.write');$b=body_json();$id=(int)req($b,'id',0);$customer=tenant_ref('customers',req($b,'customer_id'),$cid,true);$email=trim((string)req($b,'email',''));if(!filter_var($email,FILTER_VALIDATE_EMAIL))json_response(['ok'=>false,'error'=>'invalid_email'],422);$password=(string)req($b,'password','');if(!$id&&strlen($password)<10)json_response(['ok'=>false,'error'=>'password_short'],422);if($id){$fields=['customer_id=?','email=?','active=?'];$args=[$customer,$email,!empty($b['active'])?1:0];if($password!==''){$fields[]='password_hash=?';$args[]=hash_password($password);}$args[]=$id;$args[]=$cid;$pdo->prepare('UPDATE v10_portal_users SET '.implode(',',$fields).' WHERE id=? AND company_id=?')->execute($args);}else{$pdo->prepare('INSERT INTO v10_portal_users(company_id,customer_id,email,password_hash,active) VALUES(?,?,?,?,?)')->execute([$cid,$customer,$email,hash_password($password),!empty($b['active'])?1:0]);$id=(int)$pdo->lastInsertId();}json_response(['ok'=>true,'id'=>$id]);
 case 'delete_portal_user':require_cap_v10('service.write');$b=body_json();$pdo->prepare('DELETE FROM v10_portal_users WHERE id=? AND company_id=?')->execute([(int)req($b,'id',0),$cid]);json_response(['ok'=>true]);
 default:json_response(['ok'=>false,'error'=>'unknown_action'],404);
}}catch(Throwable $e){error_log($e->__toString());json_response(['ok'=>false,'error'=>'server_error','message'=>envv('APP_ENV','local')==='local'?$e->getMessage():'Internal server error'],500);}
